unit FMMOVORDEMSAIDA;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, FMPADRAOGERAL, Data.DB,
  ZAbstractRODataset, ZAbstractDataset, ZDataset, Vcl.Menus, Vcl.StdCtrls,
  Vcl.DBCtrls, Vcl.ExtCtrls, cxGraphics, cxControls, cxLookAndFeels,
  cxLookAndFeelPainters, cxContainer, cxEdit, dxSkinsCore,
  dxSkinsDefaultPainters, cxTextEdit, cxMaskEdit, cxDropDownEdit, cxCalendar,
  cxDBEdit, Vcl.Buttons, Vcl.Mask, cxStyles, dxSkinscxPCPainter, cxCustomData,
  cxFilter, cxData, cxDataStorage, cxNavigator, cxDBData, cxGridLevel,
  cxClasses, cxGridCustomView, cxGridCustomTableView, cxGridTableView,
  cxGridDBTableView, cxGrid, Vcl.ComCtrls, Vcl.Imaging.jpeg, ZStoredProcedure,
  frxClass, frxDBSet;

type
  TFMMOVORDEMSAIDA1 = class(TFMPADRAOGERAL1)
    GroupBox1: TGroupBox;
    RG_SELECAO: TRadioGroup;
    Panel1: TPanel;
    Label1: TLabel;
    Label2: TLabel;
    DBTXTCOD_ORCAMENTO: TDBEdit;
    Label4: TLabel;
    DBTXTCOD_CLIENTE: TDBEdit;
    BIB_BUSCA_CLIENTE: TBitBtn;
    TXTCLIENTE: TEdit;
    Label3: TLabel;
    DBTXTOBSERVACAO: TDBEdit;
    Label5: TLabel;
    DBTXTDATA_INICIAL: TcxDBDateEdit;
    Label6: TLabel;
    DBTXTDATA_FINAL: TcxDBDateEdit;
    GroupBox2: TGroupBox;
    Panel2: TPanel;
    Label7: TLabel;
    Label27: TLabel;
    Label8: TLabel;
    DBTXTCOD_SERVICO: TDBEdit;
    BIB_BUSCA_SERVICO: TBitBtn;
    TXTNOME_SERVICO: TEdit;
    DBTXTVALOR_SERVICO: TDBEdit;
    DBTXTQUANTIDADE: TDBEdit;
    Panel3: TPanel;
    BTNCONFIRMAR_SERVICO: TBitBtn;
    BTNCANCELAR_SERVICO: TBitBtn;
    BTNEXCLUIR_SERVICO: TBitBtn;
    GroupBox3: TGroupBox;
    DBGRIDITENS: TcxGrid;
    DBGRIDITENSDBTableView1: TcxGridDBTableView;
    DBGRIDITENSLevel1: TcxGridLevel;
    GroupBox4: TGroupBox;
    Label12: TLabel;
    Label14: TLabel;
    Label15: TLabel;
    Label16: TLabel;
    DBTXTTOTAL_SEM_DESCONTO: TDBEdit;
    DBTXTDESCONTO: TDBEdit;
    DBTXTVLR_DESCONTO: TDBEdit;
    DBTXTTOTAL_COM_DESCONTO: TDBEdit;
    Panel4: TPanel;
    BTNFINALIZAR: TBitBtn;
    BitBtn4: TBitBtn;
    BTNCANCELAR: TBitBtn;
    QRYPARAM: TZQuery;
    QRYPARAMCOD_TERMINAL: TWideStringField;
    QRYPARAMCOD_APLIC_CHAMA: TWideStringField;
    QRYPARAMNOME_PARAM: TWideStringField;
    QRYPARAMPARAM_C1: TWideStringField;
    QRYPARAMPARAM_C2: TWideStringField;
    QRYPARAMPARAM_C3: TWideStringField;
    QRYPARAMPARAM_C4: TWideStringField;
    QRYPARAMPARAM_C5: TWideStringField;
    QRYPARAMPARAM_C6: TWideStringField;
    QRYPARAMPARAM_C7: TWideStringField;
    QRYPARAMPARAM_C8: TWideStringField;
    QRYPARAMPARAM_C9: TWideStringField;
    QRYPARAMPARAM_C10: TWideStringField;
    QRYPARAMPARAM_N1: TFloatField;
    QRYPARAMPARAM_N2: TFloatField;
    QRYPARAMPARAM_N3: TFloatField;
    QRYPARAMPARAM_N4: TFloatField;
    QRYPARAMPARAM_N5: TFloatField;
    QRYPARAMPARAM_N6: TFloatField;
    QRYPARAMPARAM_N7: TFloatField;
    QRYPARAMPARAM_N8: TFloatField;
    QRYPARAMPARAM_N9: TFloatField;
    QRYPARAMPARAM_N10: TFloatField;
    QRYPARAMPARAM_N11: TFloatField;
    QRYPARAMPARAM_N12: TFloatField;
    QRYPARAMPARAM_N13: TFloatField;
    QRYPARAMPARAM_N14: TFloatField;
    QRYPARAMPARAM_N15: TFloatField;
    QRYPARAMPARAM_N16: TFloatField;
    QRYPARAMPARAM_N17: TFloatField;
    QRYPARAMPARAM_N18: TFloatField;
    QRYPARAMPARAM_N19: TFloatField;
    QRYPARAMPARAM_N20: TFloatField;
    QRYPARAMPARAM_D1: TDateTimeField;
    QRYPARAMPARAM_D2: TDateTimeField;
    QRYPARAMPARAM_D3: TDateTimeField;
    QRYPARAMPARAM_D4: TDateTimeField;
    QRYPARAMPARAM_D5: TDateTimeField;
    QRYPARAMPARAM_D6: TDateTimeField;
    QRYPARAMPARAM_D7: TDateTimeField;
    QRYPARAMPARAM_D8: TDateTimeField;
    QRYPARAMPARAM_D9: TDateTimeField;
    QRYPARAMPARAM_D10: TDateTimeField;
    QRYPARAMPARAM_N21: TFloatField;
    QRYPARAMPARAM_N22: TFloatField;
    QRYPARAMPARAM_N23: TFloatField;
    QRYPARAMPARAM_N24: TFloatField;
    QRYPARAMPARAM_N25: TFloatField;
    QRYPARAMPARAM_N26: TFloatField;
    QRYPARAMPARAM_N27: TFloatField;
    QRYPARAMPARAM_N28: TFloatField;
    QRYPARAMPARAM_N29: TFloatField;
    QRYPARAMPARAM_N30: TFloatField;
    QRYPARAMPARAM_D11: TDateTimeField;
    QRYPARAMPARAM_D12: TDateTimeField;
    QRYPARAMPARAM_D13: TDateTimeField;
    QRYPARAMPARAM_D14: TDateTimeField;
    QRYPARAMPARAM_D15: TDateTimeField;
    QRYPARAMPARAM_D16: TDateTimeField;
    QRYPARAMPARAM_D17: TDateTimeField;
    QRYPARAMPARAM_D18: TDateTimeField;
    QRYPARAMPARAM_D19: TDateTimeField;
    QRYPARAMPARAM_D20: TDateTimeField;
    QRYPARAMPARAM_N31: TFloatField;
    QRYPARAMPARAM_N32: TFloatField;
    QRYPARAMPARAM_N33: TFloatField;
    QRYPARAMPARAM_N34: TFloatField;
    QRYPARAMPARAM_N35: TFloatField;
    QRYPARAMPARAM_C11: TWideStringField;
    QRYPARAMPARAM_C12: TWideStringField;
    QRYPARAMPARAM_C13: TWideStringField;
    QRYPARAMPARAM_C14: TWideStringField;
    QRYPARAMPARAM_C15: TWideStringField;
    QRYPARAMPARAM_C16: TWideStringField;
    QRYPARAMPARAM_C17: TWideStringField;
    QRYPARAMPARAM_C18: TWideStringField;
    QRYPARAMPARAM_C19: TWideStringField;
    QRYPARAMPARAM_C20: TWideStringField;
    QRYPARAMPARAM_C21: TWideStringField;
    QRYPARAMPARAM_C22: TWideStringField;
    QRYPARAMPARAM_C23: TWideStringField;
    QRYPARAMPARAM_C24: TWideStringField;
    QRYPARAMPARAM_C25: TWideStringField;
    QRYPARAMPARAM_N36: TFloatField;
    QRYPARAMPARAM_N37: TFloatField;
    QRYPARAMPARAM_N38: TFloatField;
    QRYPARAMPARAM_N39: TFloatField;
    QRYPARAMPARAM_N40: TFloatField;
    QRYPARAMPARAM_N41: TFloatField;
    QRYPARAMPARAM_N42: TFloatField;
    QRYPARAMPARAM_N43: TFloatField;
    QRYPARAMPARAM_N44: TFloatField;
    QRYPARAMPARAM_N45: TFloatField;
    QRYPARAMPARAM_N46: TFloatField;
    QRYPARAMPARAM_N47: TFloatField;
    QRYPARAMPARAM_N48: TFloatField;
    QRYPARAMPARAM_N49: TFloatField;
    QRYPARAMPARAM_N50: TFloatField;
    QRYPARAMPARAM_N51: TFloatField;
    QRYPARAMPARAM_N52: TFloatField;
    QRYPARAMPARAM_N53: TFloatField;
    QRYPARAMPARAM_N54: TFloatField;
    QRYPARAMPARAM_N55: TFloatField;
    QRYPARAMPARAM_N56: TFloatField;
    QRYPARAMPARAM_N57: TFloatField;
    QRYPARAMPARAM_N58: TFloatField;
    QRYPARAMPARAM_N59: TFloatField;
    QRYPARAMPARAM_N60: TFloatField;
    QRYPARAMPARAM_C26: TWideStringField;
    QRYPARAMPARAM_C100: TWideStringField;
    DSPARAM: TDataSource;
    PCINSEREITENS_TEMP: TZStoredProc;
    QRYITENS: TZQuery;
    QRYITENSNUM2: TFloatField;
    QRYITENSNUM3: TFloatField;
    QRYITENSNUM4: TFloatField;
    QRYITENSNUM5: TFloatField;
    QRYITENSNOME_SERVICO: TWideStringField;
    QRYITENSTIPOREGISTRO: TWideStringField;
    QRYITENSVLR_ITEM: TFloatField;
    QRYITENSPERTENCE_SERV_TERCEIRO: TWideStringField;
    QRYHEADER_ORCAMENTO: TZQuery;
    QRYHEADER_ORCAMENTOCOD_ORCAMENTO: TFloatField;
    QRYHEADER_ORCAMENTOCOD_EMPRESA: TFloatField;
    QRYHEADER_ORCAMENTOCOD_CLIENTE: TFloatField;
    QRYHEADER_ORCAMENTODESCRICAO: TWideStringField;
    QRYHEADER_ORCAMENTOSITUACAO: TWideStringField;
    QRYHEADER_ORCAMENTODATA_INICIAL_VIGENCIA: TDateTimeField;
    QRYHEADER_ORCAMENTODATA_FINAL_VIGENCIA: TDateTimeField;
    QRYHEADER_ORCAMENTOOBSERVACOES: TWideStringField;
    QRYHEADER_ORCAMENTOVALOR_TOTAL: TFloatField;
    QRYHEADER_ORCAMENTOVALOR_DESCONTO: TFloatField;
    QRYHEADER_ORCAMENTODATA_CADASTRO: TDateTimeField;
    QRYHEADER_ORCAMENTOMOTIVO_DESCONTO: TWideStringField;
    QRYHEADER_ORCAMENTOVALOR_SERV_TERCEIRO: TFloatField;
    QRYHEADER_ORCAMENTOUSUA_RESPONSAVEL: TWideStringField;
    DSITENS: TDataSource;
    DBGRIDITENSDBTableView1NUM3: TcxGridDBColumn;
    DBGRIDITENSDBTableView1NOME_SERVICO: TcxGridDBColumn;
    DBGRIDITENSDBTableView1VLR_ITEM: TcxGridDBColumn;
    PCGERA_TOTAIS_ORCAMENTO: TZStoredProc;
    PCFINALIZA_OS: TZStoredProc;
    BIB_BUSCA_ORCAMENTO: TBitBtn;
    FRXDBHEADER: TfrxDBDataset;
    FRXDBITENS: TfrxDBDataset;
    frxOS: TfrxReport;
    QRYRELITENS_OS: TZQuery;
    QRYRELITENS_OSCOD_SERVICO: TFloatField;
    QRYRELITENS_OSCOD_OS: TFloatField;
    QRYRELITENS_OSCOD_EMPRESA: TFloatField;
    QRYRELITENS_OSCOD_CLIENTE: TFloatField;
    QRYRELITENS_OSVALOR_SERV_INDIVIDUAL: TFloatField;
    QRYRELITENS_OSQUANTIDADE_SERVICO: TFloatField;
    QRYRELITENS_OSTEM_SERV_TERCEIRO: TWideStringField;
    QRYRELITENS_OSVALOR_SERV_TERCEIRO: TFloatField;
    QRYRELITENS_OSCOD_SERVICO_TERCEIRO: TFloatField;
    QRYRELITENS_OSNOME_SERVICO: TWideStringField;
    QRYRELITENS_OSVLR_TOTAL: TFloatField;
    QRYRELHEADER_OS: TZQuery;
    QRYRELHEADER_OSCOD_OS: TFloatField;
    QRYRELHEADER_OSCOD_EMPRESA: TFloatField;
    QRYRELHEADER_OSCOD_CLIENTE: TFloatField;
    QRYRELHEADER_OSSITUACAO: TWideStringField;
    QRYRELHEADER_OSVALOR_TOTAL: TFloatField;
    QRYRELHEADER_OSVALOR_DESCONTO: TFloatField;
    QRYRELHEADER_OSDATA_INICIO: TDateTimeField;
    QRYRELHEADER_OSDATA_PREVISAO_FIM: TDateTimeField;
    QRYRELHEADER_OSOBSERVACOES: TWideStringField;
    QRYRELHEADER_OSTEM_ORCAMENTO_RELACIONADO: TWideStringField;
    QRYRELHEADER_OSCOD_ORCAMENTO_RELAC: TFloatField;
    QRYRELHEADER_OSMOTIVO_DESCONTO: TWideStringField;
    QRYRELHEADER_OSUSUARIO_LIBEROU_DESC: TFloatField;
    QRYRELHEADER_OSUSUARIO_EXE: TWideStringField;
    QRYRELHEADER_OSDATA_TERMINO: TDateTimeField;
    QRYRELHEADER_OSNOME_NOME_FANTASIA_CLIENTE: TWideStringField;
    QRYRELHEADER_OSCOD_USUARIO_RESPONSAVEL: TFloatField;
    QRYRELHEADER_OSNOME_NOME_FANTASIA: TWideStringField;
    QRYRELHEADER_OSCPF: TWideStringField;
    QRYRELHEADER_OSCNPJ: TWideStringField;
    QRYRELHEADER_OSTIPO_PESSOA: TWideStringField;
    QRYRELHEADER_OSENDERECO: TWideStringField;
    QRYRELHEADER_OSNUMERO: TFloatField;
    QRYRELHEADER_OSCOMPLEMENTO: TWideStringField;
    QRYRELHEADER_OSBAIRRO: TWideStringField;
    QRYRELHEADER_OSCEP: TWideStringField;
    QRYRELHEADER_OSEMAIL: TWideStringField;
    QRYRELHEADER_OSNOME_EMPRESA: TWideStringField;
    QRYRELHEADER_OSTELEFONE_CELULAR: TWideStringField;
    QRYRELHEADER_OSCIDADE: TWideStringField;
    QRYRELHEADER_OSUF: TWideStringField;
    QRYHEADER_ORCAMENTOPORCENTAGEM_DESCONTO: TFloatField;
    DBGRIDITENSDBTableView1NUM5: TcxGridDBColumn;
    DBTXTCOD_OS: TDBEdit;
    Label18: TLabel;
    Label9: TLabel;
    Label10: TLabel;
    Label11: TLabel;
    Label13: TLabel;
    procedure BTNCANCELARClick(Sender: TObject);
    procedure FormShow(Sender: TObject);
    procedure RG_SELECAOClick(Sender: TObject);
    procedure BIB_BUSCA_CLIENTEClick(Sender: TObject);
    procedure DBTXTCOD_CLIENTEExit(Sender: TObject);
    PROCEDURE HABILITA_CAMPOS(PESTADO: BOOLEAN);
    procedure BIBPONTOS_PRINCIPALClick(Sender: TObject);
    procedure CARREGA_ITENS;
    PROCEDURE DELETA_TEMPORARIA;
    procedure CARREGA_TOTAIS;
    procedure BIB_BUSCA_SERVICOClick(Sender: TObject);
    procedure DBTXTCOD_SERVICOExit(Sender: TObject);
    procedure BTNCANCELAR_SERVICOClick(Sender: TObject);
    procedure BTNCONFIRMAR_SERVICOClick(Sender: TObject);
    procedure BTNFINALIZARClick(Sender: TObject);
    procedure BTNEXCLUIR_SERVICOClick(Sender: TObject);
    procedure DBGRIDITENSDBTableView1DblClick(Sender: TObject);
    procedure DBTXTDESCONTOExit(Sender: TObject);
    procedure BIB_BUSCA_ORCAMENTOClick(Sender: TObject);
    procedure DBTXTCOD_ORCAMENTOExit(Sender: TObject);
    procedure CARREGAR_RELATORIO;
    procedure QRYPARAMAfterInsert(DataSet: TDataSet);
    procedure MNUAJUDAClick(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;
   // 1 - ao clicar em finalizar OS , SE TIVER DESCONTO ABRIR TELA PARA O USUARIO INFORMAR O MOTIVO DO DESCONTO
   // 2 - AO INCLUIR SERVIÇO, SE TIVER SERVIÇO DE TERCEIRO , ABRIR TELA PARA ELE SELECIONAR QUAIS SERVIÇOS ELE QUER.
var
  FMMOVORDEMSAIDA1: TFMMOVORDEMSAIDA1;

implementation

{$R *.dfm}

uses DMPRINCIPAL, UNROTINASGERAIS, FMPADRAOFILTRO, FMPADRAOCONSULTA,
  FMMOVORDEMSAIDA2;

procedure TFMMOVORDEMSAIDA1.BIBPONTOS_PRINCIPALClick(Sender: TObject);
begin
  inherited;
  {if QRYPARAMPARAM_N2.AsString = '' then
  begin
    MESSAGEDLG('Informe o código do orçamento para prosseguir!',mtInformation,[MBOK],1);
    DBTXTCOD_ORCAMENTO.SetFocus;
    Abort;
  end; }
  IF QRYPARAMPARAM_N2.ASSTRING <> '' THEN
  BEGIN
    QRYHEADER_ORCAMENTO.CLOSE;
    QRYHEADER_ORCAMENTO.SQL.Clear;
    QRYHEADER_ORCAMENTO.SQL.Add('SELECT * FROM TBHEADER_ORCAMENTO');
    QRYHEADER_ORCAMENTO.SQL.Add('WHERE COD_ORCAMENTO = :PCOD_ORCAMENTO AND ');
    QRYHEADER_ORCAMENTO.SQL.Add('      COD_EMPRESA   = :PCOD_EMPRESA   AND');
    QRYHEADER_ORCAMENTO.SQL.Add('      DATA_FINAL_VIGENCIA >= SYSDATE');
    QRYHEADER_ORCAMENTO.ParamByName('PCOD_ORCAMENTO').AsInteger := QRYPARAMPARAM_N2.AsInteger;
    QRYHEADER_ORCAMENTO.ParamByName('PCOD_EMPRESA').AsInteger   := EMPRESA_ATUAL;
    QRYHEADER_ORCAMENTO.Open;

    if QRYHEADER_ORCAMENTO.IsEmpty then
    BEGIN
      MESSAGEDLG('Orçamento não encontrado ou fora do prazo de vigencia.'+CHR(13)+'Informe um código válido do orçamento para prosseguir!',mtInformation,[MBOK],1);
      DBTXTCOD_ORCAMENTO.SetFocus;
      Abort;
    END;


    QRYPARAMPARAM_N3.AsInteger  := QRYHEADER_ORCAMENTOCOD_CLIENTE.AsInteger;
    DBTXTCOD_CLIENTEExit(SELF);
    {QRYPARAMPARAM_D1.AsDateTime := QRYHEADER_ORCAMENTODATA_INICIAL_VIGENCIA.AsDateTime;
    QRYPARAMPARAM_D2.AsDateTime := QRYHEADER_ORCAMENTODATA_FINAL_VIGENCIA.AsDateTime;}
    QRYPARAMPARAM_C1.AsString   := QRYHEADER_ORCAMENTOOBSERVACOES.AsString;
    //QRYPARAMPARAM_C1.AsString   := QRYAUX.FieldByName('OBSERVACOES').ASSTRING;

    PCINSEREITENS_TEMP.ParamByName('PCOD_TERMINAL').AsString    := BUSCANOME_COMPUTADOR;
    PCINSEREITENS_TEMP.ParamByName('PCOD_APLICACAO').AsString   := 'FMMOVORDEMSAIDA';
    PCINSEREITENS_TEMP.ParamByName('PCOD_EMPRESA').ASINTEGER    := EMPRESA_ATUAL;
    PCINSEREITENS_TEMP.ParamByName('PCOD_ORCAMENTO').ASINTEGER  := QRYPARAMPARAM_N2.ASINTEGER;
    PCINSEREITENS_TEMP.ParamByName('PCOD_CLIENTE').ASINTEGER    := QRYPARAMPARAM_N3 .ASINTEGER;
    PCINSEREITENS_TEMP.Prepare;
    PCINSEREITENS_TEMP.ExecProc;
    PCINSEREITENS_TEMP.Unprepare;


    //CARREGA_TOTAIS;
    CARREGA_ITENS;

    HABILITA_CAMPOS(TRUE);
    DBTXTCOD_SERVICO.SETFOCUS;
  END;


end;

procedure TFMMOVORDEMSAIDA1.BIB_BUSCA_CLIENTEClick(Sender: TObject);
var S_FILTRO : STRING;
begin
  inherited;
  S_FILTRO := 'COD_EMPRESA  = '+INTTOSTR(EMPRESA_ATUAL)+
              'AND SITUACAO = ''A''   ';
  FMPADRAOCONSULTA1.QRY.CLOSE;
  IF FMPADRAOCONSULTA1.PADRAOCONSULTA (
        'NOME_NOME_FANTASIA', 'COD_CLIENTE "Codigo", NOME_NOME_FANTASIA "Nome", DECODE(TIPO_PESSOA,''F'',''Fisica'',''J'',''Juridica'') "Tipo Pessoa"',
        S_FILTRO, 'Nome do cliente', 'NOME_NOME_FANTASIA',
        'TBCLIENTE', 'S', 'Clientes', TRUE
     ) THEN
  BEGIN
     QRYPARAMPARAM_N3.ASINTEGER := FMPADRAOCONSULTA1.QRY.FIELDBYNAME('Codigo').ASINTEGER;
     DBTXTCOD_CLIENTEExit(SELF);
  END;
end;

procedure TFMMOVORDEMSAIDA1.BIB_BUSCA_ORCAMENTOClick(Sender: TObject);
var S_FILTRO : STRING;
begin
  inherited;
 S_FILTRO := 'COD_EMPRESA = '+INTTOSTR(EMPRESA_ATUAL)+
             'AND SITUACAO = ''A'''+
             'AND DATA_FINAL_VIGENCIA >= SYSDATE' ;
  FMPADRAOCONSULTA1.QRY.CLOSE;
  IF FMPADRAOCONSULTA1.PADRAOCONSULTA (
        'NOME_NOME_FANTASIA_CLIENTE', 'COD_ORCAMENTO "Codigo", NOME_NOME_FANTASIA_CLIENTE "Nome Cliente",'+
        'DATA_INICIAL_VIGENCIA "Data Inicial Vigencia", DATA_FINAL_VIGENCIA  "Data Final Vigencia",'+
        '''R$'' || VALOR_TOTAL "Valor Total",''R$'' || VALOR_DESCONTO "Valor Desconto", DATA_CADASTRO "Dt. Cadastro"'
        ,S_FILTRO, 'Nome Cliente', 'COD_ORCAMENTO',
        'TBHEADER_ORCAMENTO', 'S', 'de Orçamentos', TRUE
     ) THEN
  BEGIN
     QRYPARAMPARAM_N2.ASINTEGER := FMPADRAOCONSULTA1.QRY.FIELDBYNAME('Codigo').ASINTEGER;
     DBTXTCOD_ORCAMENTOEXIT(SELF);
  END;
end;
procedure TFMMOVORDEMSAIDA1.BIB_BUSCA_SERVICOClick(Sender: TObject);
var S_FILTRO : STRING;
begin
  inherited;
  S_FILTRO := 'COD_EMPRESA  = '+INTTOSTR(EMPRESA_ATUAL)+
              'AND SITUACAO = ''A''   ';
  FMPADRAOCONSULTA1.QRY.CLOSE;
  IF FMPADRAOCONSULTA1.PADRAOCONSULTA (
        'NOME_SERVICO', 'COD_SERVICO "Codigo", NOME_SERVICO "Nome",''R$'' ||VALOR "Valor serviço"',
        S_FILTRO, 'Nome do serviço', 'COD_SERVICO',
        'TBSERVICOS', 'S', 'Serviços', TRUE
     ) THEN
  BEGIN
     QRYPARAMPARAM_N4.ASINTEGER := FMPADRAOCONSULTA1.QRY.FIELDBYNAME('Codigo').ASINTEGER;
     DBTXTCOD_SERVICOExit(SELF);
  END;
end;

procedure TFMMOVORDEMSAIDA1.BTNCANCELARClick(Sender: TObject);
begin
  inherited;
   DELETA_TEMPORARIA;
   QRYPARAM.CANCEL;
   QRYPARAM.CLOSE;
   QRYPARAM.OPEN;
   QRYPARAM.INSERT;

   QRYPARAMPARAM_D1.ASDATETIME := DATE;
   QRYPARAMPARAM_D2.ASDATETIME := DATE+3;
   QRYPARAMPARAM_N8.ASFLOAT := 0;


   {RG_SELECAO.ItemIndex := 1;
   RG_SELECAOCLICK(SELF);}

   QRYAUX.Close;
   QRYAUX.SQL.Clear;
   QRYAUX.SQL.Add('SELECT NVL(MAX(A.COD_OS),0)+1 COD_OS FROM TBHEADERORDEM_SERVICO A');
   QRYAUX.SQL.Add('WHERE A.COD_EMPRESA = :PCOD_EMPRESA');
   QRYAUX.ParamByName('PCOD_EMPRESA').AsInteger := EMPRESA_ATUAL;
   QRYAUX.Open;

   QRYPARAMPARAM_N1.AsInteger := QRYAUX.FieldByName('COD_OS').AsInteger;
   TXTNOME_SERVICO.Text := '';
   TXTCLIENTE.Text      := '';
   QRYITENS.Close;

end;

procedure TFMMOVORDEMSAIDA1.BTNCANCELAR_SERVICOClick(Sender: TObject);
begin
  inherited;
   QRYPARAMPARAM_N4.CLEAR;
   QRYPARAMPARAM_N5.CLEAR;
   QRYPARAMPARAM_N6.CLEAR;
   QRYPARAMPARAM_C3.CLEAR;
   TXTNOME_SERVICO.TEXT := '';
   DBTXTCOD_SERVICO.SetFocus;
end;

procedure TFMMOVORDEMSAIDA1.BTNCONFIRMAR_SERVICOClick(Sender: TObject);
begin
  inherited;
   IF QRYPARAMPARAM_N3.ASSTRING = '' THEN
   BEGIN
     MessageDlg('Informe um cliente para prosseguir',mtInformation,[MBOK],0);
     DBTXTCOD_CLIENTE.SETFOCUS;
     ABORT;
   END;

   IF QRYPARAMPARAM_D1.ASSTRING = '' THEN
   BEGIN
     MessageDlg('Informe uma data de início para prosseguir',mtInformation,[MBOK],0);
     DBTXTDATA_INICIAL.SETFOCUS;
     ABORT;
   END;

   IF QRYPARAMPARAM_D2.ASSTRING = '' THEN
   BEGIN
     MessageDlg('Informe uma data de previsão final para prosseguir',mtInformation,[MBOK],0);
     DBTXTDATA_FINAL.SETFOCUS;
     ABORT;
   END;

   IF QRYPARAMPARAM_D1.ASDATETIME > QRYPARAMPARAM_D2.ASDATETIME THEN
   BEGIN
     MessageDlg('A data Inicial não pode ser maior do que a Data de Previsão Final',mtInformation,[MBOK],0);
     DBTXTDATA_INICIAL.SETFOCUS;
     ABORT;
   END;

   IF QRYPARAMPARAM_N4.ASSTRING = '' THEN
   BEGIN
     MessageDlg('Informe um serviço para prosseguir',mtInformation,[MBOK],0);
     DBTXTCOD_SERVICO.SETFOCUS;
     ABORT;
   END;

   IF QRYPARAMPARAM_N6.ASINTEGER <= 0 THEN
   BEGIN
     MessageDlg('A quantidade informada deve ser maior do que 0.',mtInformation,[MBOK],0);
     DBTXTQUANTIDADE.SETFOCUS;
     ABORT;
   END;

   QRYAUX.Close;
   QRYAUX.SQL.Clear;
   QRYAUX.SQL.Add('SELECT COUNT(1) "QTDE"');
   QRYAUX.SQL.Add('FROM TBTEMPORARIA');
   QRYAUX.SQL.Add('WHERE CODTERMINAL   = :PCOD_TERMINAL AND  ');
   QRYAUX.SQL.Add('      COD_APLICACAO = :PCOD_APLICACAO AND');
   QRYAUX.SQL.Add('      TIPOREGISTRO  = ''T'' AND');
   QRYAUX.SQL.Add('      NUM1          = :PCOD_EMPRESA AND');
   QRYAUX.SQL.Add('      NUM2          = :PCOD_CLIENTE AND');
   QRYAUX.SQL.Add('      NUM3          = :PCOD_SERVICO ');
   //QRYAUX.SQL.Add('      CHAVE         = :PCHAVE ');
   QRYAUX.PARAMBYNAME('PCOD_TERMINAL').ASSTRING  := BUSCANOME_COMPUTADOR;
   QRYAUX.PARAMBYNAME('PCOD_APLICACAO').ASSTRING := 'FMMOVORDEMSAIDA';
   QRYAUX.PARAMBYNAME('PCOD_EMPRESA').ASINTEGER  := EMPRESA_ATUAL;
   QRYAUX.PARAMBYNAME('PCOD_CLIENTE').ASINTEGER  := QRYPARAMPARAM_N3.ASINTEGER;
   QRYAUX.PARAMBYNAME('PCOD_SERVICO').ASINTEGER  := QRYPARAMPARAM_N4.ASINTEGER  ;
   //QRYAUX.PARAMBYNAME('PCHAVE').ASSTRING         := QRYPARAMPARAM_N3.ASSTRING+QRYPARAMPARAM_N4.ASSTRING;
   QRYAUX.OPEN;
   TRY
     IF QRYAUX.FIELDBYNAME('QTDE').ASINTEGER > 0 THEN
     BEGIN
        QRYAUX.CLOSE;
        QRYAUX.SQL.CLEAR;
        QRYAUX.SQL.Add('UPDATE TBTEMPORARIA');
        QRYAUX.SQL.Add('SET NUM4 = :PNUM4, ');
        QRYAUX.SQL.Add('    NUM5 = :PNUM5');
        QRYAUX.SQL.Add('WHERE CODTERMINAL   = :PCOD_TERMINAL AND  ');
        QRYAUX.SQL.Add('      COD_APLICACAO = :PCOD_APLICACAO AND');
        QRYAUX.SQL.Add('      TIPOREGISTRO  = ''T'' AND');
        QRYAUX.SQL.Add('      NUM1          = :PCOD_EMPRESA AND');
        QRYAUX.SQL.Add('      NUM2          = :PCOD_CLIENTE AND');
        QRYAUX.SQL.Add('      NUM3          = :PCOD_SERVICO ');
        //QRYAUX.SQL.Add('      CHAVE         = :PCHAVE  ');
        QRYAUX.PARAMBYNAME('PCOD_TERMINAL').ASSTRING  := BUSCANOME_COMPUTADOR;
        QRYAUX.PARAMBYNAME('PCOD_APLICACAO').ASSTRING := 'FMMOVORDEMSAIDA';
        QRYAUX.PARAMBYNAME('PCOD_EMPRESA').ASINTEGER  := EMPRESA_ATUAL;
        QRYAUX.PARAMBYNAME('PCOD_CLIENTE').ASINTEGER  := QRYPARAMPARAM_N3.ASINTEGER;
        QRYAUX.PARAMBYNAME('PCOD_SERVICO').ASINTEGER  := QRYPARAMPARAM_N4.ASINTEGER  ;
        //QRYAUX.PARAMBYNAME('PCHAVE').ASSTRING         := QRYPARAMPARAM_N3.ASSTRING+QRYPARAMPARAM_N4.ASSTRING;
        QRYAUX.PARAMBYNAME('PNUM4').ASFLOAT           := QRYPARAMPARAM_N5.ASFLOAT;
        QRYAUX.PARAMBYNAME('PNUM5').ASINTEGER         := QRYPARAMPARAM_N6.ASINTEGER;
        QRYAUX.EXECSQL;

     END
     ELSE
     BEGIN
        QRYAUX.CLOSE;
        QRYAUX.SQL.CLEAR;
        QRYAUX.SQL.ADD('INSERT INTO TBTEMPORARIA(');
        QRYAUX.SQL.ADD('CODTERMINAL,COD_APLICACAO,TIPOREGISTRO,CHAVE,');
        QRYAUX.SQL.ADD('NUM1,NUM2,NUM3,NUM4,NUM5)');
        QRYAUX.SQL.ADD('VALUES(');
        QRYAUX.SQL.ADD(':PCODTERMINAL,:PCOD_APLICACAO,:PTIPOREGISTRO,:PCHAVE,');
        QRYAUX.SQL.ADD(':PNUM1,:PNUM2,:PNUM3,:PNUM4,:PNUM5)');
        QRYAUX.PARAMBYNAME('PCODTERMINAL').ASSTRING   := BUSCANOME_COMPUTADOR;
        QRYAUX.PARAMBYNAME('PCOD_APLICACAO').ASSTRING := 'FMMOVORDEMSAIDA';
        QRYAUX.PARAMBYNAME('PTIPOREGISTRO').ASSTRING  := 'T';
        QRYAUX.PARAMBYNAME('PCHAVE').ASSTRING         := QRYPARAMPARAM_N3.ASSTRING+QRYPARAMPARAM_N4.ASSTRING;  // ORÇAMENTO + COD_SERVICO
        QRYAUX.PARAMBYNAME('PNUM1').ASINTEGER         := EMPRESA_ATUAL;
        QRYAUX.PARAMBYNAME('PNUM2').ASINTEGER         := QRYPARAMPARAM_N3.ASINTEGER; // cod_cliente
        QRYAUX.PARAMBYNAME('PNUM3').ASINTEGER         := QRYPARAMPARAM_N4.ASINTEGER; // cod_servico
        QRYAUX.PARAMBYNAME('PNUM4').ASFLOAT           := QRYPARAMPARAM_N5.ASFLOAT;   // valor_item
        QRYAUX.PARAMBYNAME('PNUM5').ASINTEGER         := QRYPARAMPARAM_N6.ASINTEGER; // quantidade
        QRYAUX.EXECSQL;
     END;
     MDPRINCIPAL.COMMIT;
   EXCEPT
     ON E:EXCEPTION DO
     BEGIN
        MDPRINCIPAL.ROLLBACK;
        MESSAGEDLG('Erro ao inserir/alterar serviço na prestação de serviço. Erro: '+CHR(13)+E.Message,mtInformation,[MBOK],0);
        DBTXTCOD_SERVICO.SetFocus;
        ABORT;
     END;
   END;
   BTNCANCELAR_SERVICOClick(self);
   //CARREGA_TOTAIS;
   CARREGA_ITENS;

end;

procedure TFMMOVORDEMSAIDA1.BTNEXCLUIR_SERVICOClick(Sender: TObject);
begin
  inherited;
    QRYAUX.Close;
    QRYAUX.SQL.Clear;
    QRYAUX.SQL.Add('SELECT COUNT(1) "QTDE"');
    QRYAUX.SQL.Add('FROM TBTEMPORARIA');
    QRYAUX.SQL.Add('WHERE CODTERMINAL   = :PCOD_TERMINAL AND  ');
    QRYAUX.SQL.Add('      COD_APLICACAO = :PCOD_APLICACAO AND');
    QRYAUX.SQL.Add('      TIPOREGISTRO  = ''T'' AND');
    QRYAUX.SQL.Add('      CHAVE         = :PCHAVE ');
    QRYAUX.PARAMBYNAME('PCOD_TERMINAL').ASSTRING  := BUSCANOME_COMPUTADOR;
    QRYAUX.PARAMBYNAME('PCOD_APLICACAO').ASSTRING := 'FMMOVORDEMSAIDA';
    IF RG_SELECAO.ItemIndex = 0 then
    BEGIN
       QRYAUX.PARAMBYNAME('PCHAVE').ASSTRING         := QRYPARAMPARAM_N2.ASSTRING+QRYPARAMPARAM_N4.ASSTRING;
    END
    ELSE
    BEGIN
      QRYAUX.PARAMBYNAME('PCHAVE').ASSTRING         := QRYPARAMPARAM_N3.ASSTRING+QRYPARAMPARAM_N4.ASSTRING;
    END;
    QRYAUX.OPEN;
    if QRYAUX.FieldByName('QTDE').AsInteger > 0 then
    BEGIN
      If  MessageDlg('Você tem certeza que deseja excluir o serviço da ordem de serviço?',mtConfirmation,[mbyes,mbno],0)=mryes
      then
      BEGIN
        TRY
          QRYAUX.Close;
          QRYAUX.SQL.Clear;
          QRYAUX.SQL.Add('DELETE');
          QRYAUX.SQL.Add('FROM TBTEMPORARIA');
          QRYAUX.SQL.Add('WHERE CODTERMINAL   = :PCOD_TERMINAL AND  ');
          QRYAUX.SQL.Add('      COD_APLICACAO = :PCOD_APLICACAO AND');
          QRYAUX.SQL.Add('      TIPOREGISTRO  = ''T'' AND');
          QRYAUX.SQL.Add('      CHAVE         = :PCHAVE ');
          QRYAUX.PARAMBYNAME('PCOD_TERMINAL').ASSTRING  := BUSCANOME_COMPUTADOR;
          QRYAUX.PARAMBYNAME('PCOD_APLICACAO').ASSTRING := 'FMMOVORDEMSAIDA';
          IF RG_SELECAO.ItemIndex = 0 then
          BEGIN
             QRYAUX.PARAMBYNAME('PCHAVE').ASSTRING         := QRYPARAMPARAM_N2.ASSTRING+QRYPARAMPARAM_N4.ASSTRING;
          END
          ELSE
          BEGIN
            QRYAUX.PARAMBYNAME('PCHAVE').ASSTRING         := QRYPARAMPARAM_N3.ASSTRING+QRYPARAMPARAM_N4.ASSTRING;
          END;
          //QRYAUX.PARAMBYNAME('PCHAVE').ASSTRING         := QRYPARAMPARAM_N3.ASSTRING+QRYPARAMPARAM_N4.ASSTRING;
          QRYAUX.EXECSQL;
        EXCEPT
        ON E:EXCEPTION DO
          BEGIN
            MESSAGEDLG('Erro ao excluir serviço do orçamento.Erro: '+CHR(13)+E.Message,MTINFORMATION,[MBOK],1);
            MDPRINCIPAL.ROLLBACK;
            BTNCANCELAR_SERVICOClick(SELF);
            DBTXTCOD_SERVICO.SetFocus;
            ABORT;
          END;
        END;
      END;
    END;
   // CARREGA_TOTAIS;
    CARREGA_ITENS;
end;

procedure TFMMOVORDEMSAIDA1.BTNFINALIZARClick(Sender: TObject);
VAR
   SMOTIVO_DESCONTO : STRING;
begin
  inherited;
   IF QRYPARAMPARAM_N3.ASSTRING = '' THEN
   BEGIN
     MessageDlg('Informe um cliente para prosseguir',mtInformation,[MBOK],0);
     DBTXTCOD_CLIENTE.SETFOCUS;
     ABORT;
   END;

   IF QRYPARAMPARAM_D1.ASSTRING = '' THEN
   BEGIN
     MessageDlg('Informe uma data inicial para prosseguir',mtInformation,[MBOK],0);
     DBTXTDATA_INICIAL.SETFOCUS;
     ABORT;
   END;

   IF QRYPARAMPARAM_D2.ASSTRING = '' THEN
   BEGIN
     MessageDlg('Informe uma data de previsão do fim para prosseguir',mtInformation,[MBOK],0);
     DBTXTDATA_FINAL.SETFOCUS;
     ABORT;
   END;

   IF QRYPARAMPARAM_D1.ASDATETIME < DATE THEN
   BEGIN
     MessageDlg('A data Inicial não pode ser menor do que a Data Atual',mtInformation,[MBOK],0);
     DBTXTDATA_INICIal.SETFOCUS;
     ABORT;
   END;

   IF QRYPARAMPARAM_D1.ASDATETIME > QRYPARAMPARAM_D2.ASDATETIME THEN
   BEGIN
     MessageDlg('A data Inicial não pode ser maior do que a Data Final',mtInformation,[MBOK],0);
     DBTXTDATA_INICIal.SETFOCUS;
     ABORT;
   END;

   IF QRYITENS.ISEMPTY THEN
   BEGIN
     MessageDlg('Informe ao menos um serviço para prosseguir',mtInformation,[MBOK],0);
     DBTXTCOD_SERVICO.SETFOCUS;
     ABORT;
   END;
   SMOTIVO_DESCONTO := '';
   IF QRYPARAMPARAM_N8.ASFLOAT > 0 THEN
   BEGIN
     TRY
        APPLICATION.CREATEFORM(TFMMOVORDEMSAIDA_2,FMMOVORDEMSAIDA_2);
        FMMOVORDEMSAIDA_2.SHOWMODAL;
        IF FMMOVORDEMSAIDA_2.BCONTINUA  THEN
        BEGIN
          SMOTIVO_DESCONTO := FMMOVORDEMSAIDA_2.TXTMOTIVO.TEXT;
        END
        ELSE
        BEGIN
          DBTXTDESCONTO.SetFocus;
          ABORT;
        END;
     FINALLY
        FMMOVORDEMSAIDA_2.FREE;
     END;
   END;


   TRY
      PCFINALIZA_OS.PARAMBYNAME('PCOD_TERMINAL').ASSTRING          := BUSCANOME_COMPUTADOR;
      PCFINALIZA_OS.PARAMBYNAME('PCOD_APLICACAO').ASSTRING         := 'FMMOVORDEMSAIDA';
      PCFINALIZA_OS.PARAMBYNAME('PCOD_EMPRESA').ASINTEGER          := EMPRESA_ATUAL;
      PCFINALIZA_OS.PARAMBYNAME('PCOD_CLIENTE').ASINTEGER          := QRYPARAMPARAM_N3.ASINTEGER;
      PCFINALIZA_OS.PARAMBYNAME('PCOD_OS').ASINTEGER               := QRYPARAMPARAM_N1.ASINTEGER;
      PCFINALIZA_OS.PARAMBYNAME('PDESCRICAO_OS').ASSTRING          := QRYPARAMPARAM_C1.AsString;
      PCFINALIZA_OS.PARAMBYNAME('PDATA_INICIO').ASDATETIME         := QRYPARAMPARAM_D1.ASDATETIME;
      PCFINALIZA_OS.PARAMBYNAME('PDATA_PREVISAO_FIM').ASDATETIME   := QRYPARAMPARAM_D2.ASDATETIME;
      PCFINALIZA_OS.PARAMBYNAME('PVALOR_TOTAL').ASFLOAT            := QRYPARAMPARAM_N10.ASFLOAT;
      PCFINALIZA_OS.PARAMBYNAME('PVALOR_DESCONTO').ASFLOAT         := QRYPARAMPARAM_N9.ASFLOAT;
      PCFINALIZA_OS.PARAMBYNAME('PUSUA_RESPONSAVEL').ASSTRING      := USUARIO_ATUAL;
      PCFINALIZA_OS.PARAMBYNAME('PMOTIVO_DESCONTO').ASSTRING       := SMOTIVO_DESCONTO;
      PCFINALIZA_OS.PARAMBYNAME('PCOD_USUARIO_RESPONSAVEL').ASINTEGER := ICOD_USUARIO_ATUAL;
      PCFINALIZA_OS.PARAMBYNAME('PCOD_ORCAMENTO_RELAC').ASINTEGER  := QRYPARAMPARAM_N2.ASINTEGER;
      PCFINALIZA_OS.PREPARE;
      PCFINALIZA_OS.EXECPROC;
      PCFINALIZA_OS.UNPREPARE;
      MDPRINCIPAL.COMMIT;
      CARREGAR_RELATORIO;
   EXCEPT
   ON E:EXCEPTION DO
     BEGIN
        MDPRINCIPAL.ROLLBACK;
        MESSAGEDLG('Erro ao finalizar Ordem de serviço. Erro: '+CHR(13)+E.Message,mtInformation,[MBOK],0);
        DBTXTCOD_CLIENTE.SetFocus;
        ABORT;
     END;
   END;

   BTNCANCELARClick(SELF);

end;

procedure TFMMOVORDEMSAIDA1.CARREGAR_RELATORIO;
begin
   QRYRELHEADER_OS.CLOSE;
   QRYRELHEADER_OS.SQL.CLEAR;
   QRYRELHEADER_OS.SQL.ADD('SELECT A.*,B.NOME_NOME_FANTASIA, B.CPF, NVL(B.CNPJ,B.CPF) "CNPJ",');
   QRYRELHEADER_OS.SQL.ADD('       B.TIPO_PESSOA, B.ENDERECO, B.NUMERO, B.COMPLEMENTO, B.BAIRRO,');
   QRYRELHEADER_OS.SQL.ADD('       B.CEP, B.EMAIL,C.RAZAO_SOCIAL "NOME_EMPRESA",');
   QRYRELHEADER_OS.SQL.ADD('       B.TELEFONE_CELULAR,D.NOME CIDADE,D.UF');
   QRYRELHEADER_OS.SQL.ADD('FROM TBHEADERORDEM_SERVICO A, TBCLIENTE B , TBEMPRESA C, TBCIDADES D');
   QRYRELHEADER_OS.SQL.ADD('WHERE A.COD_OS      = :PCOD_OS AND');
   QRYRELHEADER_OS.SQL.ADD('      A.COD_EMPRESA = :PCOD_EMPRESA AND');
   QRYRELHEADER_OS.SQL.ADD('      A.COD_CLIENTE = :PCOD_CLIENTE AND');
   QRYRELHEADER_OS.SQL.ADD('      B.COD_EMPRESA = A.COD_EMPRESA AND');
   QRYRELHEADER_OS.SQL.ADD('      B.COD_CLIENTE = A.COD_CLIENTE AND ');
   QRYRELHEADER_OS.SQL.ADD('      C.COD_EMPRESA = A.COD_EMPRESA AND');
   QRYRELHEADER_OS.SQL.ADD('      D.COD_IBGE    = B.COD_CIDADE');
   QRYRELHEADER_OS.PARAMBYNAME('PCOD_OS').ASINTEGER := QRYPARAMPARAM_N1.ASINTEGER;
   QRYRELHEADER_OS.PARAMBYNAME('PCOD_EMPRESA').ASINTEGER   := EMPRESA_ATUAL;
   QRYRELHEADER_OS.PARAMBYNAME('PCOD_CLIENTE').ASINTEGER   := QRYPARAMPARAM_N3.ASINTEGER;
   QRYRELHEADER_OS.OPEN;
   QRYRELHEADER_OS.ACTIVE := TRUE;


   QRYRELITENS_OS.CLOSE;
   QRYRELITENS_OS.SQL.CLEAR;
   QRYRELITENS_OS.SQL.ADD('SELECT A.*, B.NOME_SERVICO, A.VALOR_SERV_INDIVIDUAL * A.QUANTIDADE_SERVICO VLR_TOTAL');
   QRYRELITENS_OS.SQL.ADD('FROM TBHEADERITENS_OS A,TBSERVICOS B ');
   QRYRELITENS_OS.SQL.ADD('WHERE A.COD_OS        = :PCOD_OS AND');
   QRYRELITENS_OS.SQL.ADD('      A.COD_EMPRESA   = :PCOD_EMPRESA AND');
   QRYRELITENS_OS.SQL.ADD('      A.COD_CLIENTE   = :PCOD_CLIENTE AND');
   QRYRELITENS_OS.SQL.ADD('      B.COD_EMPRESA   = A.COD_EMPRESA AND ');
   QRYRELITENS_OS.SQL.ADD('      B.COD_SERVICO   = A.COD_SERVICO ');
   QRYRELITENS_OS.PARAMBYNAME('PCOD_OS').ASINTEGER        := QRYPARAMPARAM_N1.ASINTEGER;
   QRYRELITENS_OS.PARAMBYNAME('PCOD_EMPRESA').ASINTEGER   := EMPRESA_ATUAL;
   QRYRELITENS_OS.PARAMBYNAME('PCOD_CLIENTE').ASINTEGER   := QRYPARAMPARAM_N3.ASINTEGER;
   QRYRELITENS_OS.OPEN;
   QRYRELITENS_OS.ACTIVE := TRUE;
   frxOS.ShowReport;
end;

procedure TFMMOVORDEMSAIDA1.CARREGA_ITENS;
begin
   CARREGA_TOTAIS;
   QRYITENS.Close;
   QRYITENS.SQL.Clear;
   QRYITENS.SQL.Add('SELECT A.NUM2, A.NUM3, A.NUM4, A.NUM5, B.NOME_SERVICO, A.TIPOREGISTRO, A.NUM4 * A.NUM5 "VLR_ITEM",');
   QRYITENS.SQL.Add('       ''N'' PERTENCE_SERV_TERCEIRO');
   QRYITENS.SQL.Add('FROM TBTEMPORARIA A, TBSERVICOS B');
   QRYITENS.SQL.Add('WHERE A.CODTERMINAL = :PCOD_TERMINAL AND');
   QRYITENS.SQL.Add('      A.COD_APLICACAO = ''FMMOVORDEMSAIDA'' AND');
   QRYITENS.SQL.Add('      A.TIPOREGISTRO = ''T'' AND');
   QRYITENS.SQL.Add('      B.COD_EMPRESA = A.NUM1 AND');
   QRYITENS.SQL.Add('      B.COD_SERVICO = A.NUM3 AND');
   QRYITENS.SQL.Add('      B.SITUACAO = ''A''');
   QRYITENS.ParamByName('PCOD_TERMINAL').AsString :=BUSCANOME_COMPUTADOR;
   QRYITENS.Open;

end;

procedure TFMMOVORDEMSAIDA1.CARREGA_TOTAIS;
begin
   TRY
      PCGERA_TOTAIS_ORCAMENTO.ParamByName('PCOD_TERMINAL').AsString  := BUSCANOME_COMPUTADOR;
      PCGERA_TOTAIS_ORCAMENTO.ParamByName('PCOD_APLICACAO').AsString := 'FMMOVORDEMSAIDA';
      PCGERA_TOTAIS_ORCAMENTO.ParamByName('PCOD_EMPRESA').ASINTEGER  := EMPRESA_ATUAL;
      PCGERA_TOTAIS_ORCAMENTO.ParamByName('PPORCENTAGEM_DESCONTO').ASFLOAT  := QRYPARAMPARAM_N8.AsFloat;
      PCGERA_TOTAIS_ORCAMENTO.Prepare;
      PCGERA_TOTAIS_ORCAMENTO.ExecProc;
      QRYPARAMPARAM_N7.AsFloat  := PCGERA_TOTAIS_ORCAMENTO.ParamByName('PVALOR_TOTAL_SEM_DESCONTO').ASFLOAT;
      QRYPARAMPARAM_N9.AsFloat  := PCGERA_TOTAIS_ORCAMENTO.ParamByName('PVALOR_DESCONTO').ASFLOAT;
      //QRYPARAMPARAM_N10.AsFloat := PCGERA_TOTAIS_ORCAMENTO.ParamByName('PVALOR_ESTIMADO').ASFLOAT;
      QRYPARAMPARAM_n10.AsFloat  := PCGERA_TOTAIS_ORCAMENTO.ParamByName('PVALOR_TOTAL_COM_DESCONTO').ASFLOAT;
      PCGERA_TOTAIS_ORCAMENTO.Unprepare;
      MDPRINCIPAL.COMMIT;
   EXCEPT
   ON E:EXCEPTION DO
     BEGIN
        MDPRINCIPAL.ROLLBACK;
        MESSAGEDLG('Erro ao calcular totais da Ordem de serviço. Erro: '+CHR(13)+E.Message,mtInformation,[MBOK],0);
        DBTXTCOD_SERVICO.SetFocus;
        ABORT;
     END;
   END;
end;

procedure TFMMOVORDEMSAIDA1.DBGRIDITENSDBTableView1DblClick(Sender: TObject);
begin
  inherited;
   if not QRYITENS.IsEmpty then
   begin
     BTNCONFIRMAR_SERVICO.ENABLED := TRUE;
     BTNEXCLUIR_SERVICO.ENABLED   := TRUE;
     QRYPARAMPARAM_N4.ASINTEGER := QRYITENSNUM3.ASINTEGER;
     DBTXTCOD_SERVICOEXIT(SELF);
     QRYPARAMPARAM_N6.ASINTEGER := QRYITENSNUM5.ASINTEGER;
   end;
end;

procedure TFMMOVORDEMSAIDA1.DBTXTCOD_CLIENTEExit(Sender: TObject);
begin
  inherited;
   IF QRYPARAMPARAM_N3.ASSTRING <> '' then
    BEGIN
      QRYAUX.Close;
      QRYAUX.SQL.Clear;
      QRYAUX.SQL.Add('SELECT NOME_NOME_FANTASIA');
      QRYAUX.SQL.Add('FROM TBCLIENTE');
      QRYAUX.SQL.Add('WHERE COD_EMPRESA  = :PCOD_EMPRESA  AND ');
      QRYAUX.SQL.Add('      COD_CLIENTE  = :PCOD_CLIENTE  AND ');
      QRYAUX.SQL.Add('      SITUACAO     = ''A'' ');
      QRYAUX.ParamByName('PCOD_EMPRESA').AsInteger := EMPRESA_ATUAL;
      QRYAUX.ParamByName('PCOD_CLIENTE').AsInteger := QRYPARAMPARAM_N3.AsInteger;
      QRYAUX.Open;

      if QRYAUX.IsEmpty then
      BEGIN
        APPLICATION.MessageBox('Cliente não encontrado',pchar(Application.Title), MB_OK + MB_ICONINFORMATION);
        DBTXTCOD_CLIENTE.SetFocus;
        abort;
      END
      ELSE
      BEGIN
        TXTCLIENTE.Text := QRYAUX.FieldByName('NOME_NOME_FANTASIA').AsString;
        QRYAUX.Close;
        QRYAUX.SQL.Clear;
        QRYAUX.SQL.Add('SELECT COUNT(1) "QTDE"');
        QRYAUX.SQL.Add('FROM TBCONTAS_RECEBER A');
        QRYAUX.SQL.Add('WHERE A.COD_EMPRESA = :PCOD_EMPRESA AND');
        QRYAUX.SQL.Add('      A.COD_CLIENTE = :PCOD_CLIENTE AND ');
        QRYAUX.SQL.Add('      A.SITUACAO = ''E'' AND');
        QRYAUX.SQL.Add('      A.DATA_VENCIMENTO < trunc(SYSDATE)');
        QRYAUX.ParamByName('PCOD_EMPRESA').AsInteger := EMPRESA_ATUAL;
        QRYAUX.ParamByName('PCOD_CLIENTE').AsInteger := QRYPARAMPARAM_N3.AsInteger;
        QRYAUX.Open;

        IF QRYAUX.FIELDBYNAME('QTDE').ASINTEGER > 0 THEN
        BEGIN
           MESSAGEDLG('O Cliente selecionado possui '+INTTOSTR(QRYAUX.FIELDBYNAME('QTDE').ASINTEGER)+' pendência(s) financeiras'
           ,mtInformation,[MBOK],1);
        END;
        if DBTXTDATA_INICIAL.CanFocus then
           DBTXTDATA_INICIAL.SetFocus;
      END;
    END
    ELSE
    BEGIN
       TXTCLIENTE.TEXT := '';
    END;
end;

procedure TFMMOVORDEMSAIDA1.DBTXTCOD_ORCAMENTOExit(Sender: TObject);
begin
  inherited;
 IF QRYPARAMPARAM_N2.ASSTRING <> '' THEN
  BEGIN
    QRYHEADER_ORCAMENTO.CLOSE;
    QRYHEADER_ORCAMENTO.SQL.Clear;
    QRYHEADER_ORCAMENTO.SQL.Add('SELECT * FROM TBHEADER_ORCAMENTO');
    QRYHEADER_ORCAMENTO.SQL.Add('WHERE COD_ORCAMENTO = :PCOD_ORCAMENTO AND ');
    QRYHEADER_ORCAMENTO.SQL.Add('      COD_EMPRESA   = :PCOD_EMPRESA   AND');
    QRYHEADER_ORCAMENTO.SQL.Add('      DATA_FINAL_VIGENCIA >= SYSDATE');
    QRYHEADER_ORCAMENTO.ParamByName('PCOD_ORCAMENTO').AsInteger := QRYPARAMPARAM_N2.AsInteger;
    QRYHEADER_ORCAMENTO.ParamByName('PCOD_EMPRESA').AsInteger   := EMPRESA_ATUAL;
    QRYHEADER_ORCAMENTO.Open;

    if QRYHEADER_ORCAMENTO.IsEmpty then
    BEGIN
      MESSAGEDLG('Orçamento não encontrado ou fora do prazo de vigência.'+CHR(13)+'Informe um código válido do orçamento para prosseguir!',mtInformation,[MBOK],1);
      DBTXTCOD_ORCAMENTO.SetFocus;
      Abort;
    END;


    QRYPARAMPARAM_N3.AsInteger  := QRYHEADER_ORCAMENTOCOD_CLIENTE.AsInteger;
    DBTXTCOD_CLIENTEExit(SELF);
    {QRYPARAMPARAM_D1.AsDateTime := QRYHEADER_ORCAMENTODATA_INICIAL_VIGENCIA.AsDateTime;
    QRYPARAMPARAM_D2.AsDateTime := QRYHEADER_ORCAMENTODATA_FINAL_VIGENCIA.AsDateTime;}
    QRYPARAMPARAM_C1.AsString   := QRYHEADER_ORCAMENTOOBSERVACOES.AsString;
    QRYPARAMPARAM_N8.ASFLOAT    := QRYHEADER_ORCAMENTOPORCENTAGEM_DESCONTO.ASFLOAT;
    //QRYPARAMPARAM_C1.AsString   := QRYAUX.FieldByName('OBSERVACOES').ASSTRING;

    PCINSEREITENS_TEMP.ParamByName('PCOD_TERMINAL').AsString    := BUSCANOME_COMPUTADOR;
    PCINSEREITENS_TEMP.ParamByName('PCOD_APLICACAO').AsString   := 'FMMOVORDEMSAIDA';
    PCINSEREITENS_TEMP.ParamByName('PCOD_EMPRESA').ASINTEGER    := EMPRESA_ATUAL;
    PCINSEREITENS_TEMP.ParamByName('PCOD_ORCAMENTO').ASINTEGER  := QRYPARAMPARAM_N2.ASINTEGER;
    PCINSEREITENS_TEMP.ParamByName('PCOD_CLIENTE').ASINTEGER    := QRYPARAMPARAM_N3 .ASINTEGER;
    PCINSEREITENS_TEMP.Prepare;
    PCINSEREITENS_TEMP.ExecProc;
    PCINSEREITENS_TEMP.Unprepare;
    CARREGA_ITENS;
    HABILITA_CAMPOS(TRUE);
    IF RG_SELECAO.ITEMINDEX = 0 THEN
    BEGIN
       // HABILITA_CAMPOS(FALSE);
       DBTXTCOD_CLIENTE.ENABLED := FALSE;
       BIB_BUSCA_CLIENTE.ENABLED := FALSE;
        //DBTXTCOD_ORCAMENTO.SetFocus;
    END
    ELSE IF RG_SELECAO.ITEMINDEX = 1 THEN
    BEGIN
        // HABILITA_CAMPOS(TRUE);
        DBTXTCOD_CLIENTE.ENABLED := TRUE;
        BIB_BUSCA_CLIENTE.ENABLED := TRUE;
         //DBTXTCOD_CLIENTE.SetFocus;
    END;
    DBTXTCOD_SERVICO.SETFOCUS;
  END;

end;

procedure TFMMOVORDEMSAIDA1.DBTXTCOD_SERVICOExit(Sender: TObject);
begin
  inherited;
  if QRYPARAMPARAM_N4.ASSTRING <> '' then
    BEGIN
        QRYAUX.CLOSE;
        QRYAUX.SQL.CLEAR;
        QRYAUX.SQL.ADD('SELECT NOME_SERVICO,VALOR,TEM_SERVI_OS_TERCEIRO');
        QRYAUX.SQL.ADD('FROM TBSERVICOS');
        QRYAUX.SQL.ADD('WHERE COD_EMPRESA  = :PCOD_EMPRESA  AND ');
        QRYAUX.SQL.ADD('      COD_SERVICO  = :PCOD_SERVICO  AND ');
        QRYAUX.SQL.ADD('      SITUACAO     = ''A'' ');
        QRYAUX.PARAMBYNAME('PCOD_EMPRESA').ASINTEGER := EMPRESA_ATUAL;
        QRYAUX.PARAMBYNAME('PCOD_SERVICO').ASINTEGER := QRYPARAMPARAM_N4.ASINTEGER;
        QRYAUX.OPEN;

        if QRYAUX.IsEmpty then
        BEGIN
          APPLICATION.MessageBox('Serviço não encontrado',pchar(Application.Title), MB_OK + MB_ICONINFORMATION);
          DBTXTCOD_SERVICO.SETFOCUS;
          BTNCANCELAR_servicoClick(SELF);
          ABORT;
        END
        ELSE
        BEGIN
          TXTNOME_SERVICO.TEXT := QRYAUX.FIELDBYNAME('NOME_SERVICO').ASSTRING;
          QRYPARAMPARAM_N5.ASFLOAT := QRYAUX.FIELDBYNAME('VALOR').ASFLOAT;
          DBTXTQUANTIDADE.SetFocus;
          {QRYPARAMPARAM_C3.ASSTRING := QRYAUX.FIELDBYNAME('TEM_SERVI_OS_TERCEIRO').ASSTRING;
          DBCTEM_SERV_TERCEIROSCHANGE(SELF); }
      END;
    END
    ELSE
    BEGIN
       TXTNOME_SERVICO.Text := '';
       QRYPARAMPARAM_N5.CLEAR;
       QRYPARAMPARAM_N6.CLEAR;
    END;

end;

procedure TFMMOVORDEMSAIDA1.DBTXTDESCONTOExit(Sender: TObject);
begin
  inherited;
  if QRYPARAMPARAM_N8.AsFloat > 100 then
  BEGIN
    MESSAGEDLG('Você não pode dar um desconto maior do que 100%.',mtInformation,[MBOK],1);
    DBTXTDESCONTO.SetFocus;
    Abort;
  END;

   //CARREGA_TOTAIS;
   CARREGA_ITENS;
end;

procedure TFMMOVORDEMSAIDA1.DELETA_TEMPORARIA;
begin
  TRY
        QRYAUX.CLOSE;
        QRYAUX.SQL.CLEAR;
        QRYAUX.SQL.Add('DELETE TBTEMPORARIA');
        QRYAUX.SQL.Add('WHERE CODTERMINAL   = :PCOD_TERMINAL AND  ');
        QRYAUX.SQL.Add('      COD_APLICACAO = :PCOD_APLICACAO ');
        QRYAUX.PARAMBYNAME('PCOD_TERMINAL').ASSTRING  := BUSCANOME_COMPUTADOR;
        QRYAUX.PARAMBYNAME('PCOD_APLICACAO').ASSTRING := 'FMMOVORDEMSAIDA';
        QRYAUX.EXECSQL;

        MDPRINCIPAL.COMMIT;
   EXCEPT
     ON E:EXCEPTION DO
     BEGIN
        MDPRINCIPAL.ROLLBACK;
        MESSAGEDLG('Erro ao deletar temporaria. Erro: '+CHR(13)+E.Message,mtInformation,[MBOK],0);
        BTNCANCELAR.SETFOCUS;
        ABORT;
     END;
   END;
end;

procedure TFMMOVORDEMSAIDA1.FormShow(Sender: TObject);
begin
  inherited;
   BTNCANCELARCLICK(SELF);
   RG_SELECAO.ItemIndex := 1;
   RG_SELECAOCLICK(SELF);
end;

procedure TFMMOVORDEMSAIDA1.HABILITA_CAMPOS(PESTADO: BOOLEAN);
begin
   DBTXTCOD_ORCAMENTO.Enabled      := NOT PESTADO;
   //BIBPONTOS_PRINCIPAL.Enabled     := NOT PESTADO;
   BIB_BUSCA_ORCAMENTO.Enabled     := NOT PESTADO;
   DBTXTCOD_CLIENTE.Enabled        := PESTADO;
   //DBC_SITUACAO.Enabled           := PESTADO;
   //DBC_SITUACAO.Enabled           := FALSE;
   DBTXTOBSERVACAO.Enabled         := PESTADO;
   DBTXTDATA_INICIAL.Enabled       := PESTADO;
   DBTXTDATA_FINAL.Enabled         := PESTADO;
   DBTXTCOD_SERVICO.Enabled        := PESTADO;
   DBTXTVALOR_SERVICO.Enabled      := PESTADO;
   DBTXTQUANTIDADE.Enabled         := PESTADO;
   //DBCTEM_SERV_TERCEIROS.Enabled  := PESTADO;
   BTNCONFIRMAR_SERVICO.Enabled    := PESTADO;
   BTNEXCLUIR_SERVICO.Enabled      := PESTADO;
   BTNCANCELAR_SERVICO.Enabled     := PESTADO;
   DBTXTTOTAL_SEM_DESCONTO.Enabled := PESTADO;
   DBTXTDESCONTO.Enabled           := PESTADO;
   DBTXTTOTAL_COM_DESCONTO.Enabled := PESTADO;
   BIB_BUSCA_CLIENTE.Enabled       := PESTADO;
   BIB_BUSCA_SERVICO.Enabled       := PESTADO;
   BTNFINALIZAR.Enabled            := PESTADO;
end;

procedure TFMMOVORDEMSAIDA1.MNUAJUDAClick(Sender: TObject);
begin
  inherited;
  ABRIR_AJUDA('17');
end;

procedure TFMMOVORDEMSAIDA1.QRYPARAMAfterInsert(DataSet: TDataSet);
begin
  inherited;
   QRYPARAMPARAM_N7.AsInteger := 0;
   QRYPARAMPARAM_N9.AsInteger := 0;
   QRYPARAMPARAM_N10.AsInteger := 0;
end;

procedure TFMMOVORDEMSAIDA1.RG_SELECAOClick(Sender: TObject);
begin
  inherited;
  BTNCANCELARCLICK(SELF);
   IF RG_SELECAO.ITEMINDEX = 0 THEN
   BEGIN
      HABILITA_CAMPOS(FALSE);
      //DBTXTCOD_CLIENTE.ENABLED := FALSE;
      //BIB_BUSCA_CLIENTE.ENABLED := FALSE;
      DBTXTCOD_ORCAMENTO.SetFocus;
   END
   ELSE IF RG_SELECAO.ITEMINDEX = 1 THEN
   BEGIN
       HABILITA_CAMPOS(TRUE);
       //DBTXTCOD_CLIENTE.ENABLED := TRUE;
       //BIB_BUSCA_CLIENTE.ENABLED := TRUE;
       DBTXTCOD_CLIENTE.SetFocus;
   END;
end;

end.
