unit FMMOVCONTROLEACESSO;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, FMPADRAOGERAL, Data.DB,
  ZAbstractRODataset, ZAbstractDataset, ZDataset, Vcl.Menus, Vcl.StdCtrls,
  Vcl.DBCtrls, Vcl.ExtCtrls, Vcl.Buttons, Vcl.Mask, Vcl.ComCtrls,
  Vcl.Imaging.jpeg, cxStyles, cxClasses;

type
  TFMMOVCONTROLEACESSO1 = class(TFMPADRAOGERAL1)
    Panel1: TPanel;
    Label4: TLabel;
    DBTXTCOD_USUARIO: TDBEdit;
    BIB_BUSCA_USUARIO: TBitBtn;
    TXTUSUARIO: TEdit;
    Panel2: TPanel;
    BTNCONFIRMAR: TBitBtn;
    BTNCANCELAR: TBitBtn;
    LBLCAD_SERV: TLabel;
    DBCCAD_SERV: TDBComboBox;
    Label1: TLabel;
    LBLCAD_USUARIO: TLabel;
    DBCCAD_USUARIO: TDBComboBox;
    Label3: TLabel;
    LBLCAD_CLIENTE: TLabel;
    DBCCAD_CLIENTE: TDBComboBox;
    Label6: TLabel;
    LBLCAD_FUNCAO: TLabel;
    DBCCAD_FUNCAO: TDBComboBox;
    Label10: TLabel;
    LBLCAD_TERCEIROS: TLabel;
    Label12: TLabel;
    LBLCAD_COND_PAGAMENTO: TLabel;
    Label14: TLabel;
    LBLCAD_DESPESAS: TLabel;
    Label16: TLabel;
    LBLCAD_TP_PAGAMENTO: TLabel;
    LBLCONS_SALDO_DEVEDOR: TLabel;
    Label20: TLabel;
    DBCCAD_TERCEIRO: TDBComboBox;
    DBCCOND_PAGAMENTO: TDBComboBox;
    DBCCAD_DESPESAS: TDBComboBox;
    DBCCAD_TP_PAGAMENTO: TDBComboBox;
    DBCCONS_SALDO_DEVEDOR: TDBComboBox;
    LBLGERA_ORCAMENTO: TLabel;
    LBLCONS_FATURAMENTO: TLabel;
    Label24: TLabel;
    LBLCONS_CLIENTE_FAT: TLabel;
    Label26: TLabel;
    LBLAGENDA_CONTAS_PAGAR: TLabel;
    Label28: TLabel;
    DBC_GERA_ORCAMENTO: TDBComboBox;
    DBCCONS_FATURAMENTO: TDBComboBox;
    DBCCONS_FAT_CLIENTE: TDBComboBox;
    DBCAGENDA_CONTAS_PAGAR: TDBComboBox;
    LBLPREST_SERV: TLabel;
    Label30: TLabel;
    LBLCONS_PRODUTIVIDADE: TLabel;
    Label32: TLabel;
    LBLCONS_CONTAS_PAGAR: TLabel;
    Label34: TLabel;
    LBLBAIXA_SALDO_DEVEDOR: TLabel;
    Label36: TLabel;
    DBCGERA_PREST_SERV: TDBComboBox;
    DBCCONS_PRODUTIVIDADE: TDBComboBox;
    DBCCONTAS_PAGAR: TDBComboBox;
    DBC_BAIXA_SALDO: TDBComboBox;
    LBLMANUT_TIT_BANCARIO: TLabel;
    Label38: TLabel;
    DBCMANUT_TIT_BANC: TDBComboBox;
    Label8: TLabel;
    Label22: TLabel;
    Label39: TLabel;
    QRYPARAM: TZQuery;
    QRYPARAMCOD_TERMINAL: TWideStringField;
    QRYPARAMCOD_APLIC_CHAMA: TWideStringField;
    QRYPARAMNOME_PARAM: TWideStringField;
    QRYPARAMPARAM_C1: TWideStringField;
    QRYPARAMPARAM_C2: TWideStringField;
    QRYPARAMPARAM_C3: TWideStringField;
    QRYPARAMPARAM_C4: TWideStringField;
    QRYPARAMPARAM_C5: TWideStringField;
    QRYPARAMPARAM_C6: TWideStringField;
    QRYPARAMPARAM_C7: TWideStringField;
    QRYPARAMPARAM_C8: TWideStringField;
    QRYPARAMPARAM_C9: TWideStringField;
    QRYPARAMPARAM_C10: TWideStringField;
    QRYPARAMPARAM_N1: TFloatField;
    QRYPARAMPARAM_N2: TFloatField;
    QRYPARAMPARAM_N3: TFloatField;
    QRYPARAMPARAM_N4: TFloatField;
    QRYPARAMPARAM_N5: TFloatField;
    QRYPARAMPARAM_N6: TFloatField;
    QRYPARAMPARAM_N7: TFloatField;
    QRYPARAMPARAM_N8: TFloatField;
    QRYPARAMPARAM_N9: TFloatField;
    QRYPARAMPARAM_N10: TFloatField;
    QRYPARAMPARAM_N11: TFloatField;
    QRYPARAMPARAM_N12: TFloatField;
    QRYPARAMPARAM_N13: TFloatField;
    QRYPARAMPARAM_N14: TFloatField;
    QRYPARAMPARAM_N15: TFloatField;
    QRYPARAMPARAM_N16: TFloatField;
    QRYPARAMPARAM_N17: TFloatField;
    QRYPARAMPARAM_N18: TFloatField;
    QRYPARAMPARAM_N19: TFloatField;
    QRYPARAMPARAM_N20: TFloatField;
    QRYPARAMPARAM_D1: TDateTimeField;
    QRYPARAMPARAM_D2: TDateTimeField;
    QRYPARAMPARAM_D3: TDateTimeField;
    QRYPARAMPARAM_D4: TDateTimeField;
    QRYPARAMPARAM_D5: TDateTimeField;
    QRYPARAMPARAM_D6: TDateTimeField;
    QRYPARAMPARAM_D7: TDateTimeField;
    QRYPARAMPARAM_D8: TDateTimeField;
    QRYPARAMPARAM_D9: TDateTimeField;
    QRYPARAMPARAM_D10: TDateTimeField;
    QRYPARAMPARAM_N21: TFloatField;
    QRYPARAMPARAM_N22: TFloatField;
    QRYPARAMPARAM_N23: TFloatField;
    QRYPARAMPARAM_N24: TFloatField;
    QRYPARAMPARAM_N25: TFloatField;
    QRYPARAMPARAM_N26: TFloatField;
    QRYPARAMPARAM_N27: TFloatField;
    QRYPARAMPARAM_N28: TFloatField;
    QRYPARAMPARAM_N29: TFloatField;
    QRYPARAMPARAM_N30: TFloatField;
    QRYPARAMPARAM_D11: TDateTimeField;
    QRYPARAMPARAM_D12: TDateTimeField;
    QRYPARAMPARAM_D13: TDateTimeField;
    QRYPARAMPARAM_D14: TDateTimeField;
    QRYPARAMPARAM_D15: TDateTimeField;
    QRYPARAMPARAM_D16: TDateTimeField;
    QRYPARAMPARAM_D17: TDateTimeField;
    QRYPARAMPARAM_D18: TDateTimeField;
    QRYPARAMPARAM_D19: TDateTimeField;
    QRYPARAMPARAM_D20: TDateTimeField;
    QRYPARAMPARAM_N31: TFloatField;
    QRYPARAMPARAM_N32: TFloatField;
    QRYPARAMPARAM_N33: TFloatField;
    QRYPARAMPARAM_N34: TFloatField;
    QRYPARAMPARAM_N35: TFloatField;
    QRYPARAMPARAM_C11: TWideStringField;
    QRYPARAMPARAM_C12: TWideStringField;
    QRYPARAMPARAM_C13: TWideStringField;
    QRYPARAMPARAM_C14: TWideStringField;
    QRYPARAMPARAM_C15: TWideStringField;
    QRYPARAMPARAM_C16: TWideStringField;
    QRYPARAMPARAM_C17: TWideStringField;
    QRYPARAMPARAM_C18: TWideStringField;
    QRYPARAMPARAM_C19: TWideStringField;
    QRYPARAMPARAM_C20: TWideStringField;
    QRYPARAMPARAM_C21: TWideStringField;
    QRYPARAMPARAM_C22: TWideStringField;
    QRYPARAMPARAM_C23: TWideStringField;
    QRYPARAMPARAM_C24: TWideStringField;
    QRYPARAMPARAM_C25: TWideStringField;
    QRYPARAMPARAM_N36: TFloatField;
    QRYPARAMPARAM_N37: TFloatField;
    QRYPARAMPARAM_N38: TFloatField;
    QRYPARAMPARAM_N39: TFloatField;
    QRYPARAMPARAM_N40: TFloatField;
    QRYPARAMPARAM_N41: TFloatField;
    QRYPARAMPARAM_N42: TFloatField;
    QRYPARAMPARAM_N43: TFloatField;
    QRYPARAMPARAM_N44: TFloatField;
    QRYPARAMPARAM_N45: TFloatField;
    QRYPARAMPARAM_N46: TFloatField;
    QRYPARAMPARAM_N47: TFloatField;
    QRYPARAMPARAM_N48: TFloatField;
    QRYPARAMPARAM_N49: TFloatField;
    QRYPARAMPARAM_N50: TFloatField;
    QRYPARAMPARAM_N51: TFloatField;
    QRYPARAMPARAM_N52: TFloatField;
    QRYPARAMPARAM_N53: TFloatField;
    QRYPARAMPARAM_N54: TFloatField;
    QRYPARAMPARAM_N55: TFloatField;
    QRYPARAMPARAM_N56: TFloatField;
    QRYPARAMPARAM_N57: TFloatField;
    QRYPARAMPARAM_N58: TFloatField;
    QRYPARAMPARAM_N59: TFloatField;
    QRYPARAMPARAM_N60: TFloatField;
    QRYPARAMPARAM_C26: TWideStringField;
    QRYPARAMPARAM_C100: TWideStringField;
    DSPARAM: TDataSource;
    QRYCONTROLE_ACESSO: TZQuery;
    QRYCONTROLE_ACESSOCOD_USUARIO: TFloatField;
    QRYCONTROLE_ACESSOCADASTRO_CLIENTES: TWideStringField;
    QRYCONTROLE_ACESSOCADASTRO_USUARIO: TWideStringField;
    QRYCONTROLE_ACESSOCADASTRO_SERVICO: TWideStringField;
    QRYCONTROLE_ACESSOCADASTRO_TIPOS_PAGAMENTO: TWideStringField;
    QRYCONTROLE_ACESSOCADASTRO_DESPESAS: TWideStringField;
    QRYCONTROLE_ACESSOCADASTRO_CONDICOES_PAG: TWideStringField;
    QRYCONTROLE_ACESSOCADASTRO_TERCEIROS: TWideStringField;
    QRYCONTROLE_ACESSOCADASTRO_EMPRESA: TWideStringField;
    QRYCONTROLE_ACESSOCADASTRO_FUNCAO: TWideStringField;
    QRYCONTROLE_ACESSOCONSULTA_SALDO_DEVEDOR: TWideStringField;
    QRYCONTROLE_ACESSOCONSULTA_CONTAS_A_PAGAR: TWideStringField;
    QRYCONTROLE_ACESSOCONSULTA_USUARIO_PRODUTIVIDADE: TWideStringField;
    QRYCONTROLE_ACESSOCONSULTA_CLIENTES_XFATURAS: TWideStringField;
    QRYCONTROLE_ACESSOCONSULTA_FATURAMENTO: TWideStringField;
    QRYCONTROLE_ACESSOGERA_ORCAMENTO: TWideStringField;
    QRYCONTROLE_ACESSOGERA_PRESTACAO_SERV: TWideStringField;
    QRYCONTROLE_ACESSOAGENDA_CONTAS_PAGAR: TWideStringField;
    QRYCONTROLE_ACESSOBAIXA_SALDO_DEVEDOR: TWideStringField;
    QRYCONTROLE_ACESSOMANUTENCAO_EM_TITULOS: TWideStringField;
    QRYCONTROLE_ACESSOCOD_EMPRESA: TFloatField;
    DSCONTROLE_ACESSO: TDataSource;
    LBLBAIXA_CONTAS_PAGAR: TLabel;
    Label5: TLabel;
    DBCBAIXA_CONTAS_PAGAR: TDBComboBox;
    QRYCONTROLE_ACESSOBAIXA_CONTAS_PAGAR: TWideStringField;
    LBL_OS_PRODUCAO: TLabel;
    Label7: TLabel;
    DBC_OS_PRODUCAO: TDBComboBox;
    QRYCONTROLE_ACESSOCONSULTA_OS_PRODUCAO: TWideStringField;
    LBLEMITE_RELATORIOS: TLabel;
    Label9: TLabel;
    DBC_EMITE_RELATORIOS: TDBComboBox;
    QRYCONTROLE_ACESSOEMITE_RELATORIOS: TWideStringField;
    LBL_BACKUP: TLabel;
    Label11: TLabel;
    DBC_BACKUP: TDBComboBox;
    QRYCONTROLE_ACESSOFAZ_BACKUP: TWideStringField;
    Label2: TLabel;
    procedure BIB_BUSCA_USUARIOClick(Sender: TObject);
    procedure BTNCANCELARClick(Sender: TObject);
    procedure FormShow(Sender: TObject);
    procedure DBTXTCOD_USUARIOExit(Sender: TObject);
    PROCEDURE HABILITAR_CAMPOS(PESTADO :BOOLEAN);
    procedure DBCCAD_CLIENTEChange(Sender: TObject);
    procedure DBCCAD_USUARIOChange(Sender: TObject);
    procedure DBCCAD_SERVChange(Sender: TObject);
    procedure DBCCAD_FUNCAOChange(Sender: TObject);
    procedure DBCCONS_FAT_CLIENTEChange(Sender: TObject);
    procedure DBCCONS_FATURAMENTOChange(Sender: TObject);
    procedure DBC_GERA_ORCAMENTOChange(Sender: TObject);
    procedure DBCAGENDA_CONTAS_PAGARChange(Sender: TObject);
    procedure DBCMANUT_TIT_BANCChange(Sender: TObject);
    procedure DBCCAD_DESPESASChange(Sender: TObject);
    procedure DBCCOND_PAGAMENTOChange(Sender: TObject);
    procedure DBCCAD_TERCEIROChange(Sender: TObject);
    procedure DBCCAD_TP_PAGAMENTOChange(Sender: TObject);
    procedure DBCCONS_SALDO_DEVEDORChange(Sender: TObject);
    procedure DBCCONTAS_PAGARChange(Sender: TObject);
    procedure DBCCONS_PRODUTIVIDADEChange(Sender: TObject);
    procedure DBCGERA_PREST_SERVChange(Sender: TObject);
    procedure DBC_BAIXA_SALDOChange(Sender: TObject);
    procedure QRYPARAMAfterInsert(DataSet: TDataSet);
    procedure DB_CHANGE;
    PROCEDURE CARREGA_VALORES;
    procedure BTNCONFIRMARClick(Sender: TObject);
    procedure DBCBAIXA_CONTAS_PAGARChange(Sender: TObject);
    procedure DBC_OS_PRODUCAOChange(Sender: TObject);
    procedure DBC_EMITE_RELATORIOSChange(Sender: TObject);
    procedure DBC_BACKUPChange(Sender: TObject);
    procedure MNUAJUDAClick(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  FMMOVCONTROLEACESSO1: TFMMOVCONTROLEACESSO1;

implementation

{$R *.dfm}

uses DMPRINCIPAL, UNROTINASGERAIS, FMPADRAOFILTRO, FMPADRAOCONSULTA;

procedure TFMMOVCONTROLEACESSO1.BIB_BUSCA_USUARIOClick(Sender: TObject);
var S_FILTRO : STRING;
begin
  inherited;
 S_FILTRO := 'COD_EMPRESA = '+INTTOSTR(EMPRESA_ATUAL)+
             'AND SITUACAO = ''A''' ;
  FMPADRAOCONSULTA1.QRY.CLOSE;
  IF FMPADRAOCONSULTA1.PADRAOCONSULTA (
        'NOME', 'COD_USUARIO "Codigo", NOME "Nome"',
        S_FILTRO, 'Nome', 'COD_USUARIO',
        'TBUSUARIO', 'S', 'Usuários', TRUE
     ) THEN
  BEGIN
     QRYPARAMPARAM_N1.ASINTEGER := FMPADRAOCONSULTA1.QRY.FIELDBYNAME('Codigo').ASINTEGER;
     DBTXTCOD_USUARIOExit(SELF);
  END;
end;

procedure TFMMOVCONTROLEACESSO1.BTNCANCELARClick(Sender: TObject);
begin
  inherited;
   QRYPARAM.CANCEL;
   QRYPARAM.CLOSE;
   QRYPARAM.OPEN;
   QRYPARAM.INSERT;
   TXTUSUARIO.TEXT := '';
   DB_CHANGE;
   HABILITAR_CAMPOS(FALSE);
   DBTXTCOD_USUARIO.SetFocus;

end;

procedure TFMMOVCONTROLEACESSO1.BTNCONFIRMARClick(Sender: TObject);
VAR SMSG :STRING;
begin
  inherited;
   QRYAUX.CLOSE;
   QRYAUX.SQL.CLEAR;
   QRYAUX.SQL.ADD('SELECT COUNT(1) "QTDE"');
   QRYAUX.SQL.ADD('FROM TBCONTROLE_ACESSO');
   QRYAUX.SQL.ADD('WHERE COD_EMPRESA = :PCOD_EMPRESA AND ');
   QRYAUX.SQL.ADD('      COD_USUARIO = :PCOD_USUARIO');
   QRYAUX.PARAMBYNAME('PCOD_EMPRESA').ASINTEGER := EMPRESA_ATUAL;
   QRYAUX.PARAMBYNAME('PCOD_USUARIO').ASINTEGER := QRYPARAMPARAM_N1.AsInteger;
   QRYAUX.OPEN;
   TRY
     IF QRYAUX.FIELDBYNAME('QTDE').ASINTEGER = 0 THEN
     BEGIN
        QRYAUX.Close;
        QRYAUX.SQL.Clear;
        QRYAUX.SQL.Add('INSERT INTO TBCONTROLE_ACESSO A(COD_USUARIO,COD_EMPRESA,');
        QRYAUX.SQL.Add('A.CADASTRO_CLIENTES, A.CADASTRO_USUARIO, A.CADASTRO_SERVICO, A.CADASTRO_TIPOS_PAGAMENTO,');
        QRYAUX.SQL.Add('A.CADASTRO_DESPESAS, A.CADASTRO_CONDICOES_PAG, A.CADASTRO_TERCEIROS, A.CADASTRO_EMPRESA,');
        QRYAUX.SQL.Add('A.CADASTRO_FUNCAO, A.CONSULTA_SALDO_DEVEDOR, A.CONSULTA_CONTAS_A_PAGAR,');
        QRYAUX.SQL.Add('A.CONSULTA_USUARIO_PRODUTIVIDADE, A.CONSULTA_CLIENTES_XFATURAS, A.CONSULTA_FATURAMENTO,');
        QRYAUX.SQL.Add('A.GERA_ORCAMENTO, A.GERA_PRESTACAO_SERV, A.AGENDA_CONTAS_PAGAR, A.MANUTENCAO_EM_TITULOS,');
        QRYAUX.SQL.Add('A.BAIXA_SALDO_DEVEDOR,A.BAIXA_CONTAS_PAGAR,A.CONSULTA_OS_PRODUCAO,EMITE_RELATORIOS,FAZ_BACKUP)');
        QRYAUX.SQL.Add('VALUES(:PCOD_USUARIO,:PCOD_EMPRESA,:PCADASTRO_CLIENTES, :PCADASTRO_USUARIO, :PCADASTRO_SERVICO, :PCADASTRO_TIPOS_PAGAMENTO,');
        QRYAUX.SQL.Add(':PCADASTRO_DESPESAS, :PCADASTRO_CONDICOES_PAG, :PCADASTRO_TERCEIROS, :PCADASTRO_EMPRESA,');
        QRYAUX.SQL.Add(':PCADASTRO_FUNCAO, :PCONSULTA_SALDO_DEVEDOR, :PCONSULTA_CONTAS_A_PAGAR,');
        QRYAUX.SQL.Add(':PCONSULTA_USUARIO_PRODUTIVIDADE, :PCONSULTA_CLIENTES_XFATURAS, :PCONSULTA_FATURAMENTO,');
        QRYAUX.SQL.Add(':PGERA_ORCAMENTO, :PGERA_PRESTACAO_SERV, :PAGENDA_CONTAS_PAGAR, :PMANUTENCAO_EM_TITULOS,');
        QRYAUX.SQL.Add(':PBAIXA_SALDO_DEVEDOR,:PBAIXA_CONTAS_PAGAR,:PCONSULTA_OS_PRODUCAO,:PEMITE_RELATORIOS,:PFAZ_BACKUP)');
        //QRYAUX.ExecSQL;
        SMSG:= 'Registro inserido com sucesso';
     END
     ELSE
     BEGIN
        QRYAUX.Close;
        QRYAUX.SQL.Clear;
        QRYAUX.SQL.Add('UPDATE TBCONTROLE_ACESSO A');
        QRYAUX.SQL.Add('SET A.CADASTRO_CLIENTES        = :PCADASTRO_CLIENTES,');
        QRYAUX.SQL.Add('    A.CADASTRO_USUARIO         = :PCADASTRO_USUARIO,');
        QRYAUX.SQL.Add('    A.CADASTRO_SERVICO         = :PCADASTRO_SERVICO,');
        QRYAUX.SQL.Add('    A.CADASTRO_TIPOS_PAGAMENTO = :PCADASTRO_TIPOS_PAGAMENTO,');
        QRYAUX.SQL.Add('    A.CADASTRO_DESPESAS        = :PCADASTRO_DESPESAS,');
        QRYAUX.SQL.Add('    A.CADASTRO_CONDICOES_PAG   = :PCADASTRO_CONDICOES_PAG,');
        QRYAUX.SQL.Add('    A.CADASTRO_TERCEIROS       = :PCADASTRO_TERCEIROS,');
        QRYAUX.SQL.Add('    A.CADASTRO_EMPRESA         = :PCADASTRO_EMPRESA,');
        QRYAUX.SQL.Add('    A.CADASTRO_FUNCAO          = :PCADASTRO_FUNCAO,');
        QRYAUX.SQL.Add('    A.CONSULTA_SALDO_DEVEDOR   = :PCONSULTA_SALDO_DEVEDOR,');
        QRYAUX.SQL.Add('    A.CONSULTA_CONTAS_A_PAGAR  = :PCONSULTA_CONTAS_A_PAGAR,');
        QRYAUX.SQL.Add('    A.CONSULTA_USUARIO_PRODUTIVIDADE = :PCONSULTA_USUARIO_PRODUTIVIDADE,');
        QRYAUX.SQL.Add('    A.CONSULTA_CLIENTES_XFATURAS = :PCONSULTA_CLIENTES_XFATURAS,');
        QRYAUX.SQL.Add('    A.CONSULTA_FATURAMENTO     = :PCONSULTA_FATURAMENTO,');
        QRYAUX.SQL.Add('    A.GERA_ORCAMENTO           = :PGERA_ORCAMENTO,');
        QRYAUX.SQL.Add('    A.GERA_PRESTACAO_SERV      = :PGERA_PRESTACAO_SERV,');
        QRYAUX.SQL.Add('    A.AGENDA_CONTAS_PAGAR      = :PAGENDA_CONTAS_PAGAR,');
        QRYAUX.SQL.Add('    A.MANUTENCAO_EM_TITULOS    = :PMANUTENCAO_EM_TITULOS,');
        QRYAUX.SQL.Add('    A.BAIXA_SALDO_DEVEDOR      = :PBAIXA_SALDO_DEVEDOR,');
        QRYAUX.SQL.Add('    A.BAIXA_CONTAS_PAGAR       = :PBAIXA_CONTAS_PAGAR,');
        QRYAUX.SQL.Add('    A.CONSULTA_OS_PRODUCAO     = :PCONSULTA_OS_PRODUCAO,');
        QRYAUX.SQL.Add('    A.EMITE_RELATORIOS         = :PEMITE_RELATORIOS,');
        QRYAUX.SQL.Add('    A.FAZ_BACKUP               = :PFAZ_BACKUP');
        QRYAUX.SQL.Add('WHERE COD_EMPRESA = :PCOD_EMPRESA AND ');
        QRYAUX.SQL.Add('      COD_USUARIO = :PCOD_USUARIO');
        SMSG:= 'Registro alterado com sucesso';
     END;

     QRYAUX.PARAMBYNAME('PCADASTRO_CLIENTES').ASSTRING         := QRYPARAMPARAM_C1.ASSTRING;
     QRYAUX.PARAMBYNAME('PCADASTRO_USUARIO').ASSTRING          := QRYPARAMPARAM_C2.ASSTRING;
     QRYAUX.PARAMBYNAME('PCADASTRO_SERVICO').ASSTRING          := QRYPARAMPARAM_C3.ASSTRING;
     QRYAUX.PARAMBYNAME('PCADASTRO_TIPOS_PAGAMENTO').ASSTRING  := QRYPARAMPARAM_C13.ASSTRING;
     QRYAUX.PARAMBYNAME('PCADASTRO_DESPESAS').ASSTRING         := QRYPARAMPARAM_C10.ASSTRING;
     QRYAUX.PARAMBYNAME('PCADASTRO_CONDICOES_PAG').ASSTRING    := QRYPARAMPARAM_C11.ASSTRING;
     QRYAUX.PARAMBYNAME('PCADASTRO_TERCEIROS').ASSTRING        := QRYPARAMPARAM_C12.ASSTRING;
     QRYAUX.PARAMBYNAME('PCADASTRO_EMPRESA').ASSTRING          := 'N';
     QRYAUX.PARAMBYNAME('PCADASTRO_FUNCAO').ASSTRING           := QRYPARAMPARAM_C4.ASSTRING;
     QRYAUX.PARAMBYNAME('PCONSULTA_SALDO_DEVEDOR').ASSTRING    := QRYPARAMPARAM_C14.ASSTRING;
     QRYAUX.PARAMBYNAME('PCONSULTA_USUARIO_PRODUTIVIDADE').ASSTRING    := QRYPARAMPARAM_C16.ASSTRING;
     QRYAUX.PARAMBYNAME('PCONSULTA_CLIENTES_XFATURAS').ASSTRING := QRYPARAMPARAM_C5.ASSTRING;
     QRYAUX.PARAMBYNAME('PCONSULTA_FATURAMENTO').ASSTRING      := QRYPARAMPARAM_C6.ASSTRING;
     QRYAUX.PARAMBYNAME('PGERA_ORCAMENTO').ASSTRING            := QRYPARAMPARAM_C7.ASSTRING;
     QRYAUX.PARAMBYNAME('PGERA_PRESTACAO_SERV').ASSTRING       := QRYPARAMPARAM_C17.ASSTRING;
     QRYAUX.PARAMBYNAME('PAGENDA_CONTAS_PAGAR').ASSTRING       := QRYPARAMPARAM_C8.ASSTRING;
     QRYAUX.PARAMBYNAME('PMANUTENCAO_EM_TITULOS').ASSTRING     := QRYPARAMPARAM_C9.ASSTRING;
     QRYAUX.PARAMBYNAME('PBAIXA_SALDO_DEVEDOR').ASSTRING       := QRYPARAMPARAM_C18.ASSTRING;
     QRYAUX.PARAMBYNAME('PCONSULTA_CONTAS_A_PAGAR').ASSTRING   := QRYPARAMPARAM_C15.ASSTRING;
     QRYAUX.PARAMBYNAME('PBAIXA_CONTAS_PAGAR').ASSTRING        := QRYPARAMPARAM_C19.ASSTRING;
     QRYAUX.PARAMBYNAME('PCONSULTA_OS_PRODUCAO').ASSTRING      := QRYPARAMPARAM_C20.ASSTRING;
     QRYAUX.PARAMBYNAME('PEMITE_RELATORIOS').ASSTRING          := QRYPARAMPARAM_C21.ASSTRING;
     QRYAUX.PARAMBYNAME('PFAZ_BACKUP').ASSTRING                := QRYPARAMPARAM_C22.ASSTRING;
     QRYAUX.PARAMBYNAME('PCOD_EMPRESA').ASINTEGER              := EMPRESA_ATUAL;
     QRYAUX.PARAMBYNAME('PCOD_USUARIO').ASINTEGER              := QRYPARAMPARAM_N1.ASINTEGER;
     QRYAUX.EXECSQL;
     MESSAGEDLG(SMSG,mtInformation,[MBOK],1);
     MDPRINCIPAL.COMMIT;
     BTNCANCELARCLICK(SELF);
   EXCEPT
     ON E:EXCEPTION DO
     BEGIN
        MESSAGEDLG('Erro ao alterar/inserir o controle de acesso para o usuário!. Erro: '+E.MESSAGE,mtInformation,[MBOK],1);
        MDPRINCIPAL.ROLLBACK;
        DBCCAD_CLIENTE.SetFocus;
        //DBTXTCOD_USUARIO.SETFOCUS;
        ABORT;
     END;
   END;
end;

procedure TFMMOVCONTROLEACESSO1.CARREGA_VALORES;
begin
   QRYCONTROLE_ACESSO.CLOSE;
   QRYCONTROLE_ACESSO.SQL.CLEAR;
   QRYCONTROLE_ACESSO.SQL.ADD('SELECT * FROM TBCONTROLE_ACESSO');
   QRYCONTROLE_ACESSO.SQL.ADD('WHERE COD_EMPRESA = :PCOD_EMPRESA AND');
   QRYCONTROLE_ACESSO.SQL.ADD('      COD_USUARIO = :PCOD_USUARIO');
   QRYCONTROLE_ACESSO.PARAMBYNAME('PCOD_EMPRESA').ASINTEGER := EMPRESA_ATUAL;
   QRYCONTROLE_ACESSO.PARAMBYNAME('PCOD_USUARIO').ASINTEGER := QRYPARAMPARAM_N1.AsInteger;
   QRYCONTROLE_ACESSO.OPEN;

   QRYPARAMPARAM_C1.ASSTRING  := QRYCONTROLE_ACESSOCADASTRO_CLIENTES.ASSTRING;
   QRYPARAMPARAM_C2.ASSTRING  := QRYCONTROLE_ACESSOCADASTRO_USUARIO.ASSTRING;
   QRYPARAMPARAM_C3.ASSTRING  := QRYCONTROLE_ACESSOCADASTRO_SERVICO.ASSTRING;
   QRYPARAMPARAM_C4.ASSTRING  := QRYCONTROLE_ACESSOCADASTRO_FUNCAO.ASSTRING;
   QRYPARAMPARAM_C5.ASSTRING  := QRYCONTROLE_ACESSOCONSULTA_CLIENTES_XFATURAS.ASSTRING;
   QRYPARAMPARAM_C6.ASSTRING  := QRYCONTROLE_ACESSOCONSULTA_FATURAMENTO.ASSTRING;
   QRYPARAMPARAM_C7.ASSTRING  := QRYCONTROLE_ACESSOGERA_ORCAMENTO.ASSTRING;
   QRYPARAMPARAM_C8.ASSTRING  := QRYCONTROLE_ACESSOAGENDA_CONTAS_PAGAR.ASSTRING;
   QRYPARAMPARAM_C9.ASSTRING  := QRYCONTROLE_ACESSOMANUTENCAO_EM_TITULOS.ASSTRING;
   QRYPARAMPARAM_C10.ASSTRING := QRYCONTROLE_ACESSOCADASTRO_DESPESAS.ASSTRING;
   QRYPARAMPARAM_C11.ASSTRING := QRYCONTROLE_ACESSOCADASTRO_CONDICOES_PAG.ASSTRING;
   QRYPARAMPARAM_C12.ASSTRING := QRYCONTROLE_ACESSOCADASTRO_TERCEIROS.ASSTRING;
   QRYPARAMPARAM_C13.ASSTRING := QRYCONTROLE_ACESSOCADASTRO_TIPOS_PAGAMENTO.ASSTRING;
   QRYPARAMPARAM_C14.ASSTRING := QRYCONTROLE_ACESSOCONSULTA_SALDO_DEVEDOR.ASSTRING;
   QRYPARAMPARAM_C15.ASSTRING := QRYCONTROLE_ACESSOCONSULTA_CONTAS_A_PAGAR.ASSTRING;
   QRYPARAMPARAM_C16.ASSTRING := QRYCONTROLE_ACESSOCONSULTA_USUARIO_PRODUTIVIDADE.ASSTRING;
   QRYPARAMPARAM_C17.ASSTRING := QRYCONTROLE_ACESSOGERA_PRESTACAO_SERV.ASSTRING;
   QRYPARAMPARAM_C18.ASSTRING := QRYCONTROLE_ACESSOBAIXA_SALDO_DEVEDOR.ASSTRING;
   QRYPARAMPARAM_C19.ASSTRING := QRYCONTROLE_ACESSOBAIXA_CONTAS_PAGAR.ASSTRING;
   QRYPARAMPARAM_C20.ASSTRING := QRYCONTROLE_ACESSOCONSULTA_OS_PRODUCAO.ASSTRING;
   QRYPARAMPARAM_C21.ASSTRING := QRYCONTROLE_ACESSOEMITE_RELATORIOS.ASSTRING;
   QRYPARAMPARAM_C22.ASSTRING := QRYCONTROLE_ACESSOFAZ_BACKUP.ASSTRING;



end;

procedure TFMMOVCONTROLEACESSO1.DBCAGENDA_CONTAS_PAGARChange(Sender: TObject);
begin
  inherited;
   IF DBCAGENDA_CONTAS_PAGAR.TEXT = 'N' THEN
   BEGIN
     LBLAGENDA_CONTAS_PAGAR.CAPTION := 'Não';
   END
   ELSE IF DBCAGENDA_CONTAS_PAGAR.TEXT = 'S' THEN
   BEGIN
      LBLAGENDA_CONTAS_PAGAR.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLAGENDA_CONTAS_PAGAR.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCBAIXA_CONTAS_PAGARChange(Sender: TObject);
begin
  inherited;
   IF DBCBAIXA_CONTAS_PAGAR.TEXT = 'N' THEN
   BEGIN
     LBLBAIXA_CONTAS_PAGAR.CAPTION := 'Não';
   END
   ELSE IF DBCBAIXA_CONTAS_PAGAR.TEXT = 'S' THEN
   BEGIN
      LBLBAIXA_CONTAS_PAGAR.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLBAIXA_CONTAS_PAGAR.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCAD_CLIENTEChange(Sender: TObject);
begin
  inherited;
   IF DBCCAD_CLIENTE.TEXT = 'N' THEN
   BEGIN
     LBLCAD_CLIENTE.CAPTION := 'Não';
   END
   ELSE IF DBCCAD_CLIENTE.TEXT = 'S' THEN
   BEGIN
      LBLCAD_CLIENTE.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCAD_CLIENTE.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCAD_DESPESASChange(Sender: TObject);
begin
  inherited;
   IF DBCCAD_DESPESAS.TEXT = 'N' THEN
   BEGIN
     LBLCAD_DESPESAS.CAPTION := 'Não';
   END
   ELSE IF DBCCAD_DESPESAS.TEXT = 'S' THEN
   BEGIN
      LBLCAD_DESPESAS.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCAD_DESPESAS.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCAD_FUNCAOChange(Sender: TObject);
begin
  inherited;
   IF DBCCAD_FUNCAO.TEXT = 'N' THEN
   BEGIN
     LBLCAD_FUNCAO.CAPTION := 'Não';
   END
   ELSE IF DBCCAD_FUNCAO.TEXT = 'S' THEN
   BEGIN
      LBLCAD_FUNCAO.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCAD_FUNCAO.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCAD_SERVChange(Sender: TObject);
begin
  inherited;
   IF DBCCAD_SERV.TEXT = 'N' THEN
   BEGIN
     LBLCAD_SERV.CAPTION := 'Não';
   END
   ELSE IF DBCCAD_SERV.TEXT = 'S' THEN
   BEGIN
      LBLCAD_SERV.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCAD_SERV.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCAD_TERCEIROChange(Sender: TObject);
begin
  inherited;
   IF DBCCAD_TERCEIRO.TEXT = 'N' THEN
   BEGIN
     LBLCAD_TERCEIROS.CAPTION := 'Não';
   END
   ELSE IF DBCCAD_TERCEIRO.TEXT = 'S' THEN
   BEGIN
      LBLCAD_TERCEIROS.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCAD_TERCEIROS.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCAD_TP_PAGAMENTOChange(Sender: TObject);
begin
  inherited;
   IF DBCCAD_TP_PAGAMENTO.TEXT = 'N' THEN
   BEGIN
     LBLCAD_TP_PAGAMENTO.CAPTION := 'Não';
   END
   ELSE IF DBCCAD_TP_PAGAMENTO.TEXT = 'S' THEN
   BEGIN
      LBLCAD_TP_PAGAMENTO.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCAD_TP_PAGAMENTO.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCAD_USUARIOChange(Sender: TObject);
begin
  inherited;
   IF DBCCAD_USUARIO.TEXT = 'N' THEN
   BEGIN
     LBLCAD_USUARIO.CAPTION := 'Não';
   END
   ELSE IF DBCCAD_USUARIO.TEXT = 'S' THEN
   BEGIN
      LBLCAD_USUARIO.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCAD_USUARIO.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCOND_PAGAMENTOChange(Sender: TObject);
begin
  inherited;
   IF DBCCOND_PAGAMENTO.TEXT = 'N' THEN
   BEGIN
     LBLCAD_COND_PAGAMENTO.CAPTION := 'Não';
   END
   ELSE IF DBCCOND_PAGAMENTO.TEXT = 'S' THEN
   BEGIN
      LBLCAD_COND_PAGAMENTO.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCAD_COND_PAGAMENTO.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCONS_FATURAMENTOChange(Sender: TObject);
begin
  inherited;
   IF DBCCONS_FATURAMENTO.TEXT = 'N' THEN
   BEGIN
     LBLCONS_FATURAMENTO.CAPTION := 'Não';
   END
   ELSE IF DBCCONS_FATURAMENTO.TEXT = 'S' THEN
   BEGIN
      LBLCONS_FATURAMENTO.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCONS_FATURAMENTO.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCONS_FAT_CLIENTEChange(Sender: TObject);
begin
  inherited;
   IF DBCCONS_FAT_CLIENTE.TEXT = 'N' THEN
   BEGIN
     LBLCONS_CLIENTE_FAT.CAPTION := 'Não';
   END
   ELSE IF DBCCONS_FAT_CLIENTE.TEXT = 'S' THEN
   BEGIN
      LBLCONS_CLIENTE_FAT.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCONS_CLIENTE_FAT.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCONS_PRODUTIVIDADEChange(Sender: TObject);
begin
  inherited;
   IF DBCCONS_PRODUTIVIDADE.TEXT = 'N' THEN
   BEGIN
     LBLCONS_PRODUTIVIDADE.CAPTION := 'Não';
   END
   ELSE IF DBCCONS_PRODUTIVIDADE.TEXT = 'S' THEN
   BEGIN
      LBLCONS_PRODUTIVIDADE.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCONS_PRODUTIVIDADE.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCONS_SALDO_DEVEDORChange(Sender: TObject);
begin
  inherited;
   IF DBCCONS_SALDO_DEVEDOR.TEXT = 'N' THEN
   BEGIN
     LBLCONS_SALDO_DEVEDOR.CAPTION := 'Não';
   END
   ELSE IF DBCCONS_SALDO_DEVEDOR.TEXT = 'S' THEN
   BEGIN
      LBLCONS_SALDO_DEVEDOR.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCONS_SALDO_DEVEDOR.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCCONTAS_PAGARChange(Sender: TObject);
begin
  inherited;
    IF DBCCONTAS_PAGAR.TEXT = 'N' THEN
   BEGIN
     LBLCONS_CONTAS_PAGAR.CAPTION := 'Não';
   END
   ELSE IF DBCCONTAS_PAGAR.TEXT = 'S' THEN
   BEGIN
      LBLCONS_CONTAS_PAGAR.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLCONS_CONTAS_PAGAR.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCGERA_PREST_SERVChange(Sender: TObject);
begin
  inherited;
   IF DBCGERA_PREST_SERV.TEXT = 'N' THEN
   BEGIN
     LBLPREST_SERV.CAPTION := 'Não';
   END
   ELSE IF DBCGERA_PREST_SERV.TEXT = 'S' THEN
   BEGIN
      LBLPREST_SERV.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLPREST_SERV.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBCMANUT_TIT_BANCChange(Sender: TObject);
begin
  inherited;
   IF DBCMANUT_TIT_BANC.TEXT = 'N' THEN
   BEGIN
     LBLMANUT_TIT_BANCARIO.CAPTION := 'Não';
   END
   ELSE IF DBCMANUT_TIT_BANC.TEXT = 'S' THEN
   BEGIN
      LBLMANUT_TIT_BANCARIO.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLMANUT_TIT_BANCARIO.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBC_BACKUPChange(Sender: TObject);
begin
  inherited;
   IF DBC_BACKUP.TEXT = 'N' THEN
   BEGIN
     LBL_BACKUP.CAPTION := 'Não';
   END
   ELSE IF DBC_BACKUP.TEXT = 'S' THEN
   BEGIN
      LBL_BACKUP.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBL_BACKUP.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBC_BAIXA_SALDOChange(Sender: TObject);
begin
  inherited;
  IF DBC_BAIXA_SALDO.TEXT = 'N' THEN
   BEGIN
     LBLBAIXA_SALDO_DEVEDOR.CAPTION := 'Não';
   END
   ELSE IF DBC_BAIXA_SALDO.TEXT = 'S' THEN
   BEGIN
      LBLBAIXA_SALDO_DEVEDOR.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLBAIXA_SALDO_DEVEDOR.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBC_EMITE_RELATORIOSChange(Sender: TObject);
begin
  inherited;
   IF DBC_EMITE_RELATORIOS.TEXT = 'N' THEN
   BEGIN
     LBLEMITE_RELATORIOS.CAPTION := 'Não';
   END
   ELSE IF DBC_EMITE_RELATORIOS.TEXT = 'S' THEN
   BEGIN
      LBLEMITE_RELATORIOS.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLEMITE_RELATORIOS.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBC_GERA_ORCAMENTOChange(Sender: TObject);
begin
  inherited;
   IF DBC_GERA_ORCAMENTO.TEXT = 'N' THEN
   BEGIN
     LBLGERA_ORCAMENTO.CAPTION := 'Não';
   END
   ELSE IF DBC_GERA_ORCAMENTO.TEXT = 'S' THEN
   BEGIN
      LBLGERA_ORCAMENTO.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBLGERA_ORCAMENTO.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBC_OS_PRODUCAOChange(Sender: TObject);
begin
  inherited;
   IF DBC_OS_PRODUCAO.TEXT = 'N' THEN
   BEGIN
     LBL_OS_PRODUCAO.CAPTION := 'Não';
   END
   ELSE IF DBC_OS_PRODUCAO.TEXT = 'S' THEN
   BEGIN
      LBL_OS_PRODUCAO.CAPTION := 'Sim';
   END
   ELSE
   BEGIN
      LBL_OS_PRODUCAO.CAPTION := '';
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DBTXTCOD_USUARIOExit(Sender: TObject);
begin
  inherited;

   if QRYPARAMPARAM_N1.AsString <> '' then
   begin
     QRYAUX.CLOSE;
     QRYAUX.SQL.Clear;
     QRYAUX.SQL.Add('SELECT NOME ');
     QRYAUX.SQL.Add('FROM TBUSUARIO');
     QRYAUX.SQL.Add('WHERE COD_EMPRESA = :PCOD_EMPRESA AND ');
     QRYAUX.SQL.Add('      COD_USUARIO = :PCOD_USUARIO AND ');
     QRYAUX.SQL.Add('      SITUACAO = ''A''');
     QRYAUX.ParamByName('PCOD_EMPRESA').ASINTEGER := EMPRESA_ATUAL;
     QRYAUX.ParamByName('PCOD_USUARIO').ASINTEGER := QRYPARAMPARAM_N1.AsInteger;
     QRYAUX.Open;

     IF QRYAUX.ISEMPTY THEN
     BEGIN
       MESSAGEDLG('Usuário não encontrado ou inativo. Informe um usuário válido para prosseguir.',MTINFORMATION,[MBOK],0);
       DBTXTCOD_USUARIO.SETFOCUS;
       ABORT;
     END;

     TXTUSUARIO.TEXT := QRYAUX.FIELDBYNAME('NOME').ASSTRING;
     {if TIPO_USUARIO = 'N' then
     BEGIN
       HABILITAR_CAMPOS(FALSE);
     END
     ELSE
     BEGIN
        HABILITAR_CAMPOS(TRUE);
     END; }
     HABILITAR_CAMPOS(TRUE);
     CARREGA_VALORES;
     DB_CHANGE;
     DBCCAD_CLIENTE.SetFocus;
   END;
end;

procedure TFMMOVCONTROLEACESSO1.DB_CHANGE;
begin
   DBCCAD_CLIENTECHANGE(SELF);
   DBCCAD_USUARIOCHANGE(SELF);
   DBCCAD_SERVCHANGE(SELF);
   DBCCAD_FUNCAOCHANGE(SELF);
   DBCCAD_TERCEIROCHANGE(SELF);
   DBCCOND_PAGAMENTOCHANGE(SELF);
   DBCCAD_DESPESASCHANGE(SELF);
   DBCCAD_TP_PAGAMENTOCHANGE(SELF);
   DBCCONS_SALDO_DEVEDORCHANGE(SELF);
   DBC_GERA_ORCAMENTOCHANGE(SELF);
   DBCCONS_FATURAMENTOCHANGE(SELF);
   DBCCONS_FAT_CLIENTECHANGE(SELF);
   DBCAGENDA_CONTAS_PAGARCHANGE(SELF);
   DBCGERA_PREST_SERVCHANGE(SELF);
   DBCCONS_PRODUTIVIDADECHANGE(SELF);
   DBCCONTAS_PAGARCHANGE(SELF);
   DBC_BAIXA_SALDOCHANGE(SELF);
   DBCMANUT_TIT_BANCCHANGE(SELF);
   DBCBAIXA_CONTAS_PAGARCHANGE(SELF);
   DBC_OS_PRODUCAOCHANGE(SELF);
   DBC_EMITE_RELATORIOSCHANGE(SELF);
   DBC_BACKUPCHANGE(SELF);
end;


procedure TFMMOVCONTROLEACESSO1.FormShow(Sender: TObject);
begin
  inherited;
   BTNCANCELARClick(SELF);
end;

procedure TFMMOVCONTROLEACESSO1.HABILITAR_CAMPOS(PESTADO: BOOLEAN);
VAR
I:INTEGER;
begin
  DBTXTCOD_USUARIO.Enabled  := NOT PESTADO;
  BIB_BUSCA_USUARIO.Enabled := NOT PESTADO;
  BTNCONFIRMAR.Enabled      := PESTADO;
  FOR I := FMMOVCONTROLEACESSO1.COMPONENTCOUNT -1 DOWNTO 0 DO
  BEGIN
    IF (FMMOVCONTROLEACESSO1.COMPONENTS[I] IS TDBComboBox) THEN
       (FMMOVCONTROLEACESSO1.COMPONENTS[I] AS TDBComboBox).Enabled := PESTADO;
  END;
end;

procedure TFMMOVCONTROLEACESSO1.MNUAJUDAClick(Sender: TObject);
begin
  inherited;
  ABRIR_AJUDA('31');
end;

procedure TFMMOVCONTROLEACESSO1.QRYPARAMAfterInsert(DataSet: TDataSet);
begin
  inherited;
   {QRYPARAMPARAM_C1.ASSTRING  := 'N';
   QRYPARAMPARAM_C2.ASSTRING  := 'N';
   QRYPARAMPARAM_C3.ASSTRING  := 'N';
   QRYPARAMPARAM_C4.ASSTRING  := 'N';
   QRYPARAMPARAM_C5.ASSTRING  := 'N';
   QRYPARAMPARAM_C6.ASSTRING  := 'N';
   QRYPARAMPARAM_C7.ASSTRING  := 'N';
   QRYPARAMPARAM_C8.ASSTRING  := 'N';
   QRYPARAMPARAM_C9.ASSTRING  := 'N';
   QRYPARAMPARAM_C10.ASSTRING := 'N';
   QRYPARAMPARAM_C11.ASSTRING := 'N';
   QRYPARAMPARAM_C12.ASSTRING := 'N';
   QRYPARAMPARAM_C13.ASSTRING := 'N';
   QRYPARAMPARAM_C14.ASSTRING := 'N';
   QRYPARAMPARAM_C15.ASSTRING := 'N';
   QRYPARAMPARAM_C16.ASSTRING := 'N';
   QRYPARAMPARAM_C17.ASSTRING := 'N';
   QRYPARAMPARAM_C18.ASSTRING := 'N';}

end;

end.
