CREATE OR REPLACE PROCEDURE PCINSEREITENS_TEMP(PCOD_TERMINAL  VARCHAR2,
                                               PCOD_APLICACAO VARCHAR2,
                                               PCOD_EMPRESA   VARCHAR2,
                                               PCOD_ORCAMENTO NUMBER,
                                               PCOD_CLIENTE   NUMBER) IS
   IQTDE               NUMBER;
   S_TEM_SERV_TERCEIRO VARCHAR2(1);
BEGIN

   DELETE FROM TBTEMPORARIA A
   WHERE A.CODTERMINAL = PCOD_TERMINAL AND
         A.COD_APLICACAO = PCOD_APLICACAO;

   FOR VITENS IN (SELECT *
                  FROM TBITENS_ORCAMENTO A
                  WHERE A.COD_ORCAMENTO = PCOD_ORCAMENTO AND
                        A.COD_EMPRESA = PCOD_EMPRESA AND
                        A.COD_CLIENTE = PCOD_CLIENTE)
   LOOP
      SELECT COUNT(1)
      INTO IQTDE
      FROM TBTEMPORARIA B
      WHERE B.CODTERMINAL = PCOD_TERMINAL AND
            B.COD_APLICACAO = PCOD_APLICACAO AND
            B.TIPOREGISTRO = 'T' AND
            B.NUM1 = PCOD_EMPRESA AND
            B.NUM2 = PCOD_CLIENTE AND
            B.NUM3 = VITENS.COD_SERVICO;
      IF IQTDE = 0 THEN
         S_TEM_SERV_TERCEIRO := 'N';
         IF VITENS.COD_SERVICO_TERCEIRO IS NOT NULL THEN
            S_TEM_SERV_TERCEIRO := 'S';
         END IF;
         INSERT INTO TBTEMPORARIA
            (CODTERMINAL, COD_APLICACAO, TIPOREGISTRO, CHAVE, NUM1, NUM2, NUM3, NUM4, NUM5, ALFA1, ALFA3)
         VALUES
            (PCOD_TERMINAL, PCOD_APLICACAO, 'T', PCOD_ORCAMENTO || VITENS.COD_SERVICO, PCOD_EMPRESA,
             PCOD_CLIENTE, VITENS.COD_SERVICO, VITENS.VALOR_SERV_INDIVIDUAL, VITENS.QUANTIDADE_SERVICO,
             S_TEM_SERV_TERCEIRO, 'S');
      
         IF S_TEM_SERV_TERCEIRO = 'S' THEN
            INSERT INTO TBTEMPORARIA
               (CODTERMINAL, COD_APLICACAO, TIPOREGISTRO, CHAVE, NUM1, NUM2, NUM3, NUM4, NUM5, ALFA2, ALFA3)
            VALUES
               (PCOD_TERMINAL, PCOD_APLICACAO, 'S', VITENS.COD_SERVICO_TERCEIRO, PCOD_EMPRESA,
                VITENS.COD_SERVICO, VITENS.COD_SERVICO_TERCEIRO, VITENS.VALOR_SERV_TERCEIRO,
                VITENS.QTDE_SERV_TERCEIRO, 'P', 'S');
         END IF;
      END IF;
   END LOOP;
   -- ITENS DE TERCEIRO INSERIDOS INDIVIDUALMENTE
   FOR VITENS_TERC IN (SELECT *
                       FROM TBITENS_ORCAMENTO_TERCEIRO A
                       WHERE A.COD_ORCAMENTO = PCOD_ORCAMENTO AND
                             A.COD_EMPRESA = PCOD_EMPRESA AND
                             A.COD_CLIENTE = PCOD_CLIENTE) -- AQUI QUANDO TIVER 'I' É QUE FOI INSERIDO INDIVIDULA
   LOOP
      INSERT INTO TBTEMPORARIA
         (CODTERMINAL, COD_APLICACAO, TIPOREGISTRO, CHAVE, NUM1, NUM2, NUM3, NUM4, NUM5, ALFA2, ALFA3,ALFA4)
      VALUES
         (PCOD_TERMINAL, PCOD_APLICACAO, 'S', VITENS_TERC.COD_SERVICO_TERC, PCOD_EMPRESA, 0,
          VITENS_TERC.COD_SERVICO_TERC, VITENS_TERC.VALOR, VITENS_TERC.QUANTIDADE_SERVICO, 'P', 'S','I');
   END LOOP;
END;
/
