CREATE OR REPLACE TRIGGER TGUSUARIO
BEFORE INSERT OR UPDATE OR DELETE ON TBUSUARIO FOR EACH ROW
DECLARE
   S_LOGIN TBUSUARIO.LOGIN%TYPE;
   IQTDE   NUMBER;
BEGIN
   IF INSERTING THEN
      BEGIN
         INSERT INTO TBCONTROLE_ACESSO
            (COD_USUARIO, COD_EMPRESA)
         VALUES
            (:NEW.COD_USUARIO, :NEW.COD_EMPRESA);
      EXCEPTION
         WHEN DUP_VAL_ON_INDEX THEN
            BEGIN
               NULL;
            END;
      END;
   
   END IF;
   IF DELETING THEN
      DELETE FROM TBCONTROLE_ACESSO
      WHERE COD_USUARIO = :OLD.COD_USUARIO AND
            COD_EMPRESA = :OLD.COD_EMPRESA;
   END IF;

END;
/
